using ElinTogether.Models;
using ElinTogether.Net;
int checks=0;void Check(bool value,string label){if(!value)throw new Exception(label);checks++;Console.WriteLine("PASS "+label);}
var host=new ElinNetHost();var client=new ElinNetClient();var actor=new Chara{uid=719};var other=new Chara{uid=1};host.ActiveRemoteCharas[1]=actor;
var item=new Thing{uid=100,parent=actor};CardCache.Items[item.uid]=item;
CardImportantDelta Request(bool value)=>new(){Card=item,Important=value,Request=true};
NetSession.Instance.Connection=client;item.c_isImportant=true;
Check(client.Delta.Items.Single() is CardImportantDelta{Important:true,Request:true},"client toggle sends explicit mark request");
Check(item.c_isImportant,"client toggle remains immediately visible");
item.Saved[109]=0;NetSession.Instance.Connection=host;client.Delta.Items.Single().Apply(host);
Check(item.c_isImportant&&item.Saved[109]==1,"host accepts own-item mark into native saved field 109");
Check(host.Delta.Items.Count==1,"request application publishes one result without setter echo");
NetSession.Instance.Connection=client;item.Saved[109]=0;var sent=client.Delta.Items.Count;host.Delta.Items.Single().Apply(client);
Check(item.c_isImportant&&client.Delta.Items.Count==sent,"authoritative result restores client flag without another request");
Check(LayerInventory.Dirty.Contains(item.uid),"flag result refreshes inventory display");
NetSession.Instance.Connection=host;Request(false).Apply(host);Check(!item.c_isImportant,"unmark reaches host as well as mark");
var repeat=Request(true);repeat.Apply(host);repeat.Apply(host);Check(item.c_isImportant,"repeated absolute mark cannot toggle back off");
Request(false).Apply(host);Check(!item.c_isImportant,"ordered mark/unmark preserves latest requested state");
item.parent=other;Request(true).Apply(host);
Check(!item.c_isImportant&&host.Replies.Last() is CardImportantDelta{Important:false,Request:false},"ownership change rejects request and returns actual state");
item.parent=actor;host.Accept=false;Request(true).Apply(host);host.Accept=true;Check(!item.c_isImportant,"break/resume input gate rejects stale request");
var bag=new Thing{uid=101,parent=actor};item.parent=bag;Request(true).Apply(host);Check(item.c_isImportant,"nested personal inventory remains owned");
var chest=new Thing{uid=102,ExistsOnMap=true,IsPCFactionOrMinion=true};item.parent=chest;Request(false).Apply(host);
Check(!item.c_isImportant,"nearby allied container supports native flag editing");
actor.Distance=9;Request(true).Apply(host);actor.Distance=1;Check(!item.c_isImportant,"distant container rejected");
chest.isNPCProperty=true;Request(true).Apply(host);chest.isNPCProperty=false;Check(!item.c_isImportant,"NPC-owned stock rejected");
var npc=new Chara{uid=55,IsPlayer=false,ExistsOnMap=true,IsPCFactionOrMinion=true};item.parent=npc;Request(true).Apply(host);
Check(item.c_isImportant,"nearby NPC ally inventory retains vanilla access");
item.parent=actor;new CardImportantDelta{Card=item,Important=false}.Apply(host);Check(item.c_isImportant,"host rejects fabricated result packets");
var before=host.Delta.Items.Count;item.c_isImportant=false;
Check(host.Delta.Items.Count==before+1&&host.Delta.Items.Last() is CardImportantDelta{Important:false,Request:false},"native host toggle broadcasts resolved state");
before=host.Delta.Items.Count;item.c_isImportant=false;Check(host.Delta.Items.Count==before,"unchanged setter does not publish noise");
item.isDestroyed=true;Request(true).Apply(host);Check(!item.c_isImportant,"destroyed item cannot be edited");item.isDestroyed=false;
NetSession.Instance.Connection=client;sent=client.Delta.Items.Count;var pending=new Thing{uid=0x40000001};CardCache.Items[pending.uid]=pending;pending.c_isImportant=true;
Check(client.Delta.Items.Count==sent,"temporary split metadata is not sent as an unknown item request");
var uncached=new Thing{uid=999};uncached.c_isImportant=true;Check(client.Delta.Items.Count==sent,"uncached construction does not publish a mark request");
item.Saved[109]=0;Request(true).Apply(client);Check(!item.c_isImportant,"client never executes another peer's request");
NetSession.Instance.Connection=null;item.c_isImportant=true;Check(item.c_isImportant&&client.Delta.Items.Count==sent,"single-player flag stays vanilla");
Console.WriteLine($"{checks} checks passed; simulated transport/game boundary, not a live reconnect test.");
