<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><OutputType>Exe</OutputType><TargetFramework>net11.0</TargetFramework><ImplicitUsings>enable</ImplicitUsings><Nullable>enable</Nullable></PropertyGroup><ItemGroup><Compile Include="../../ElinTogether/Models/Delta/Chara/CharaSwitchHeldDelta.cs" Link="CharaSwitchHeldDelta.cs"/><Compile Include="../../ElinTogether/Elements/GoalRemote.cs" Link="GoalRemote.cs"/></ItemGroup></Project>
