using ElinTogether.Elements;
using ElinTogether.Models;
using ElinTogether.Net;
void Check(bool value,string name){if(!value)throw new Exception(name);Console.WriteLine("PASS "+name);}
var net=new ElinNetBase{IsHost=true};
var owner=new Chara{uid=719};var root=new GoalRemote();root.SetOwner(owner);owner.ai=root;
var pick=new Thing{uid=1,parent=owner};var axe=new Thing{uid=2,parent=owner};var sickle=new Thing{uid=3,parent=owner};owner.held=pick;
CharaSwitchHeldDelta Switch(Card? item)=>new(){Owner=owner,HeldMainHand=item is null?null:(RemoteCard)item,HeldOffHand=item is null?null:(RemoteCard)item};
root.child=new AIAct();Switch(axe).Apply(net);
Check(owner.held==pick && root.PendingHeld!=null,"running task retains original tool and queues switch");
var next=new BaseTaskHarvest();root.InsertAction(next);
Check(owner.held==axe && next.Captured==axe && root.PendingHeld==null,"next harvest snapshots deferred axe instead of stale pick");
Switch(pick).Apply(net);Switch(sickle).Apply(net);root.HaltChildAct();
Check(owner.held==sickle,"latest switch wins while task runs");
root.child=new AIAct();Switch(null).Apply(net);root.HaltChildAct();
Check(owner.held==null,"empty-hand switch also survives running task");
root.child=new AIAct();Switch(pick).Apply(net);root.child.status=AIAct.Status.Success;Switch(axe).Apply(net);root.HaltChildAct();
Check(owner.held==axe && root.PendingHeld==null,"new idle switch supersedes queued switch");
root.child=new AIAct();Switch(sickle).Apply(net);var foreign=new Chara();sickle.parent=foreign;root.HaltChildAct();
Check(owner.held==axe,"deferred switch cannot take an item that changed owner");
owner.IsPC=true;Switch(pick).Apply(net);
Check(owner.held==axe,"remote replication does not overwrite local player tool");
owner.IsPC=false;root.child=new AIAct();Switch(pick).Apply(net);var before=net.Delta.Items.Count;root.HaltChildAct();
Check(net.Delta.Items.Count==before,"applying pending switch does not rebroadcast packet");
root.child=new AIAct();Switch(axe).Apply(net);root.child.status=AIAct.Status.Success;
var run=root.Run().GetEnumerator();run.MoveNext();run.MoveNext();
Check(owner.held==axe && root.PendingHeld==null,"normal goal cleanup applies queued switch without a new task");

CharaTaskDelta Task(Card? tool,TaskArgsBase? args=null)=>new(){Owner=owner,TaskArgs=args??new HarvestArgs(),Tool=tool is null?null:(RemoteCard)tool};
root.HaltChildAct();owner.held=axe;Task(pick).Apply(net);
Check(owner.held==pick && ((BaseTaskHarvest)root.child!).Captured==pick,"task arriving before visual tool update captures requested pick");
Switch(axe).Apply(net);Task(pick).Apply(net);
Check(owner.held==pick && ((BaseTaskHarvest)root.child!).Captured==pick,"task tool supersedes deferred stale visual switch before snapshot");
Task(null).Apply(net);
Check(owner.held==null && ((BaseTaskHarvest)root.child!).Captured==null,"barehand harvest explicitly clears stale tool");
var oldChild=root.child;var cancelled=TaskCache.Cancelled;Task(sickle).Apply(net);
Check(root.child==oldChild && TaskCache.Cancelled==cancelled+1 && sickle.parent==foreign,"foreign tool is rejected without stealing or replacing task");
pick.isDestroyed=true;Task(pick).Apply(net);
Check(root.child==oldChild && TaskCache.Cancelled==cancelled+2,"destroyed selected tool rejects task");pick.isDestroyed=false;
owner.held=axe;Task(pick,new IdleArgs()).Apply(net);
Check(owner.held==axe,"non-harvest tasks leave tool alone");
owner.IsPC=true;oldChild=root.child;Task(pick).Apply(new ElinNetBase());
Check(root.child==oldChild && owner.held==axe,"relayed task does not reassign local player's tool");owner.IsPC=false;
TaskCache.Taken=true;cancelled=TaskCache.Cancelled;Task(pick).Apply(net);
Check(owner.held==axe && TaskCache.Cancelled==cancelled+1,"occupied tile rejection precedes tool mutation");TaskCache.Taken=false;
Task(pick).Apply(new ElinNetBase());
Check(owner.held==pick && ((BaseTaskHarvest)root.child!).Captured==pick,"observer reproduces task with supplied tool");
