<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><OutputType>Exe</OutputType><TargetFramework>net11.0</TargetFramework><ImplicitUsings>enable</ImplicitUsings><Nullable>enable</Nullable></PropertyGroup>
  <ItemGroup>
    <Compile Include="../../ElinTogether/Models/SocialInteractions.cs" Link="SocialInteractions.cs" />
    <Compile Include="../../ElinTogether/Models/Delta/Misc/SocialStateDelta.cs" Link="SocialStateDelta.cs" />
    <Compile Include="../../ElinTogether/Models/Delta/Chara/CharaGiveGiftDelta.cs" Link="CharaGiveGiftDelta.cs" />
    <Compile Include="../../ElinTogether/Models/Pending/PendingSplit.cs" Link="PendingSplit.cs" />
    <Compile Include="../../ElinTogether/Patches/DeltaEvents/Chara/CharaGiveGiftEvent.cs" Link="CharaGiveGiftEvent.cs" />
    <Compile Include="../../ElinTogether/Patches/Synchronization/SocialInteractionPatch.cs" Link="SocialInteractionPatch.cs" />
    <Compile Include="../../ElinTogether/Models/Delta/Task/AI/AIMassageArgs.cs" Link="AIMassageArgs.cs" />
    <Compile Include="../../ElinTogether/Models/Delta/Task/AI/AIArmPillowArgs.cs" Link="AIArmPillowArgs.cs" />
  </ItemGroup>
</Project>
