using ElinTogether.Models;
using ElinTogether.Net;
using ElinTogether.Patches;
using Mono.Cecil;

int checks = 0;
void Check(bool ok, string why) { if (!ok) throw new Exception(why); Console.WriteLine("PASS " + why); checks++; }
using var module = ModuleDefinition.ReadModule(args.Single());
MethodDefinition Method(string type, string name) => module.Types.Single(t => t.Name == type).Methods.Single(m => m.Name == name);
string[] Calls(MethodDefinition m) => m.Body.Instructions.Where(i => i.Operand is MethodReference).Select(i => ((MethodReference)i.Operand).Name).ToArray();
var calls = Calls(Method("QuestDeliver", "Deliver"));
Check(Array.IndexOf(calls, "Split") < Array.IndexOf(calls, "Complete") && calls.Contains("GetBonus"), "installed delivery consumes/splits and calculates bonus before completion");
Check(Method("QuestDeliver", "ListDestThing").Body.Instructions.Any(i => i.Operand is FieldReference { Name: "stocked" }), "native eligibility includes stocked settlement items");
Check(Calls(Method("QuestDeliver", "OnStart")).Contains("Pick"), "native acceptance gives delivery goods to current actor");
Check(Calls(Method("Quest", "Complete")).Contains("OnDropReward") && Calls(Method("Quest", "Complete")).Contains("ModKarma"), "native completion awards rewards and karma and must run once");

var host = new ElinNetHost(); var client = new ElinNetClient(); var hostActor = EClass.pc;
var actor = new Chara { uid = 719 }; var npc = new Chara { uid = 42 }; host.ActiveRemoteCharas[1] = actor;
NetSession.Instance.Connection = host;
QuestDeliver Make(int uid = 100) { var q = new QuestDeliver { uid = uid }; q.person.chara = npc; npc.quest = q; return q; }
QuestAcceptDelta Accept(Quest q) => new() { Uid = q.uid, ZoneUid = 10, Client = npc };
var quest = Make();
Check(SharedQuests.CanClientAccept(quest), "ordinary random quest supported");
quest.source.drama = ["story"];
Accept(quest).Apply(host);
Check(quest.Starts == 0 && !SharedQuests.CanClientAccept(quest), "dialogue restriction enforced at host acceptance");
quest.source.drama = []; quest.UseInstanceZone = true; Accept(quest).Apply(host);
Check(quest.Starts == 0, "instance quest stays host initiated");
quest.UseInstanceZone = false; quest.uid = -1; Accept(quest).Apply(host);
Check(quest.Starts == 0, "client-created quest ID cannot be accepted"); quest.uid = 100;
quest.Visible = false; Accept(quest).Apply(host);
Check(quest.Starts == 0, "native availability checked again on host");
quest.Visible = true; host.AcceptInput = false; Accept(quest).Apply(host);
Check(quest.Starts == 0, "inactive peer cannot accept"); host.AcceptInput = true;
new QuestAcceptDelta { Uid = quest.uid, Client = npc, ZoneUid = 9 }.Apply(host);
Check(quest.Starts == 0, "stale zone cannot accept");
Accept(quest).Apply(host); Accept(quest).Apply(host);
Check(quest.Starts == 1 && quest.StartedAs == actor && EClass.pc == hostActor, "accept once as requesting character, restore host context");
var full = Make(200);
var fillers = Enumerable.Range(0, 4).Select(i => new Quest { uid = 300 + i }).ToArray();
EClass.game.quests.list.AddRange(fillers); Accept(full).Apply(host);
Check(full.Starts == 0 && EClass.pc == hostActor, "shared quest limit enforced without changing actor context");
foreach (var filler in fillers) EClass.game.quests.list.Remove(filler);
npc.quest = quest;
var item = new Thing { uid = 55 }; actor.Inventory.Add(item);
QuestDeliverDelta Delivery(Quest q, Thing t, Chara? to = null) => new() { Uid = q.uid, ZoneUid = 10, Recipient = to ?? npc, Item = t };
quest.Expired = true; Delivery(quest, item).Apply(host);
Check(item.Num == 3 && quest.Deliveries == 0, "expired quest cannot consume item"); quest.Expired = false;
Delivery(quest, item, new Chara()).Apply(host);
Check(item.Num == 3, "wrong recipient cannot consume item");
item.Important = true; Delivery(quest, item).Apply(host);
Check(item.Num == 3, "important item rejected by native eligibility"); item.Important = false;
item.Equipped = true; Delivery(quest, item).Apply(host);
Check(item.Num == 3, "equipped item rejected"); item.Equipped = false;
item.Num = 1; Delivery(quest, item).Apply(host);
Check(item.Num == 1, "insufficient stack cannot partially satisfy delivery"); item.Num = 3;
actor.Inventory.Remove(item); hostActor.Inventory.Add(item); Delivery(quest, item).Apply(host);
Check(item.Num == 3, "client cannot deliver host inventory");
hostActor.Inventory.Remove(item); quest.Stock.Add(item);
Delivery(quest, item).Apply(host); Delivery(quest, item).Apply(host);
Check(item.Num == 1 && quest.Deliveries == 1 && quest.Completed == 1, "eligible settlement stock consumed once despite duplicate request");
Check(quest.CompletedAs == actor && EClass.pc == hostActor && PersonalKarma.Actor == null && !ElinDelta.IsApplying, "delivery awards run in actor context and scopes restore");
var carried = Make(103); EClass.game.quests.list.Add(carried); actor.Inventory.Add(item); item.Num = 3;
Delivery(carried, item).Apply(host);
Check(carried.Deliveries == 1 && item.Num == 1, "client inventory delivery consumes exact quest quantity");
actor.Inventory.Remove(item);
var fail = Make(101); EClass.game.quests.list.Add(fail); actor.Inventory.Add(item); item.Num = 3; fail.ThrowOnDeliver = true;
try { Delivery(fail, item).Apply(host); } catch (InvalidOperationException) { }
Check(EClass.pc == hostActor && PersonalKarma.Actor == null && !ElinDelta.IsApplying && item.Num == 3, "native exception restores all scopes");
new QuestCompleteDelta { Uid = fail.uid }.Apply(host);
Check(!fail.isComplete && fail.Completed == 0, "bare client completion packet cannot award rewards");

NetSession.Instance.Connection = client;
bool result = true;
QuestDeliverEvent.Before(fail, npc, item, ref result);
Check(!result && item.Num == 3 && client.Delta.Items.Single() is QuestDeliverDelta, "client turn-in sends intent without consuming or declaring success");
var story = new Quest { IsRandomQuest = false };
Check(!QuestDeliverEvent.Before(story, npc, item, ref result) && client.Delta.Items.Count == 1, "unsupported scripted turn-in cannot mutate locally");
ElinDelta.IsApplying = true;
QuestDeliverEvent.Before(fail, npc, item, ref result);
ElinDelta.IsApplying = false;
Check(client.Delta.Items.Count == 1, "host replay cannot emit another delivery intent");
Check(!QuestCompleteEvent.OnClientComplete(fail) && EClass.game.quests.list.Contains(fail), "client spontaneous completion preserves pending journal");
QuestCompleteEvent.OnQuestComplete(fail);
Check(client.Delta.Items.Count == 1, "client completion emits no reward request");
new QuestCompleteDelta { Uid = fail.uid }.Apply(client);
new QuestCompleteDelta { Uid = fail.uid }.Apply(client);
Check(fail.isComplete && fail.Completed == 0 && fail.Messages == 1 && item.Num == 3, "host result updates journal once with no rewards or item replay");
var guild = Make(102); guild.Guild = true; EClass.game.quests.list.Add(guild);
new QuestCompleteDelta { Uid = guild.uid }.Apply(client);
Check(!guild.isComplete, "guild completion remains on its existing authoritative channel");
NetSession.Instance.Connection = null;
Check(QuestCompleteEvent.OnClientComplete(guild) && QuestDeliverEvent.Before(guild, npc, item, ref result), "solo keeps native completion and delivery");
NetSession.Instance.Connection = host;
Check(QuestCompleteEvent.OnClientComplete(guild) && QuestDeliverEvent.Before(guild, npc, item, ref result), "host keeps native completion and delivery");
Console.WriteLine($"{checks} quest checks passed; installed native IL checked, transport/game boundaries simulated.");
