using ElinTogether.Net;
using ElinTogether.Models;
using ElinTogether.Patches;
int count=0;
void Check(bool ok,string name) { if(!ok) throw new Exception(name); count++; Console.WriteLine("PASS "+name); }
var host=new ElinNetHost(); var client=new ElinNetClient(); NetSession.Instance.Connection=client;
var map=EClass._map; map.Seen.Add(5);
MapRevealSyncPatch.Before(map,out var scope);
MapRevealCellPatch.Before(map,1,1,true); MapRevealCellPatch.Before(map,2,1,true);
MapRevealCellPatch.Before(map,2,1,true); MapRevealCellPatch.Before(map,0,0,false);
MapRevealCellPatch.Before(map,-1,0,true);
MapRevealSyncPatch.After(scope,null);
var packet=(MapRevealDelta)client.Delta.Sent.Single();
Check(packet.Cells.ToHashSet().SetEquals([5,6]),"capture exact unique revealed area including previously known tiles");
Check(MapRevealSyncPatch.Current==null,"capture scope restored");
MapRevealCellPatch.Before(map,3,3,true);
Check(client.Delta.Sent.Count==1,"ordinary exploration sends no magic-map packet");
MapRevealSyncPatch.Before(map,out scope); MapRevealCellPatch.Before(map,0,0,true);
MapRevealSyncPatch.After(scope,new Exception());
Check(client.Delta.Sent.Count==1 && MapRevealSyncPatch.Current==null,"failed reveal restores scope without publishing");
map.Seen.Clear(); packet.OriginPeer=3; packet.Apply(host);
Check(map.Seen.Count==0,"unknown sender rejected");
host.ActiveRemoteCharas[3]=new Chara(); packet.Apply(host);
Check(map.Seen.SetEquals([5,6]) && host.Delta.Sent.Count==1,"host applies exact client result and relays");
map.Seen.Clear(); packet.Apply(client);
Check(map.Seen.SetEquals([5,6]),"other client receives same tiles");
packet.Apply(client); Check(map.Seen.Count==2,"duplicate reveal is idempotent");
EClass._zone.uid=8; map.Seen.Clear(); packet.Apply(client);
Check(map.Seen.Count==0,"stale-zone reveal ignored"); EClass._zone.uid=7;
new MapRevealDelta {ZoneUid=7,Size=4,Cells=[1,99],OriginPeer=3}.Apply(host);
Check(map.Seen.Count==0,"entire invalid report rejected before partial mutation");
host.ActiveRemoteCharas[3].IsInActiveMap=false; packet.Apply(host);
Check(map.Seen.Count==0,"off-map sender rejected");
NetSession.Instance.Connection=host; var card=new Card { c_charges=5 };
CardChargeEvent.Before(card,out var before); card.c_charges=4; CardChargeEvent.OnChargeChanged(card,before);
Check(host.Delta.Sent.Last() is CardChargeDelta {Charges:4},"charge change publishes absolute host value");
var sent=host.Delta.Sent.Count; CardChargeEvent.OnChargeChanged(card,4);
Check(host.Delta.Sent.Count==sent,"unchanged charge produces no packet");
CardChargeEvent.Before(card,out before); card.c_charges=9; CardChargeEvent.OnChargeChanged(card,before);
Check(host.Delta.Sent.Last() is CardChargeDelta {Charges:9},"direct recharge assignment follows same path");
NetSession.Instance.Connection=client; sent=client.Delta.Sent.Count; CardChargeEvent.OnChargeChanged(card,0);
Check(client.Delta.Sent.Count==sent,"client prediction cannot publish charge authority");
NetSession.Instance.Connection=host; sent=host.Delta.Sent.Count; CardCache.Cached=false; CardChargeEvent.OnChargeChanged(card,0);
Check(host.Delta.Sent.Count==sent,"initialization outside card cache does not publish");
CardCache.Cached=true; card.isDestroyed=true; CardChargeEvent.OnChargeChanged(card,0);
Check(host.Delta.Sent.Count==sent,"destroyed card ignored");
Console.WriteLine($"{count} checks passed");
