using ElinTogether.Patches;
using Mono.Cecil;
int checks=0;void Check(bool ok,string name){if(!ok)throw new Exception(name);checks++;Console.WriteLine("PASS "+name);}
Core.delta=.02f;Core.gameDelta=0;EClass.game.gameSpeedIndex=2;
ActionModeCombat.Activated=true;RenderObject.gameSpeed=1;RenderObject.gameDelta=.02f;
var c=new Chara{actTime=.6f,pos=new(1,1)};
CombatPresentation.Record(c,.26f,3);
CombatPresentation.Before(c.renderer,out var state);
Check(RenderObject.gameSpeed==12&&RenderObject.gameDelta==.24f,"received run multiplier survives decision pause and receiver turbo differences");
Check(c.actTime==.26f,"remote animation uses sender duration instead of reconstructed NPC cost");
Check(Core.gameDelta==0,"rendering never advances simulation");
CombatPresentation.After(c.renderer,state);
Check(c.actTime==.6f&&RenderObject.gameSpeed==1&&RenderObject.gameDelta==.02f,"finalizer restores turn cost and global render clock");
CombatPresentation.Record(c,.26f,1);CombatPresentation.Before(c.renderer,out state);
Check(RenderObject.gameSpeed==4,"next walking step replaces previous running pace");CombatPresentation.After(c.renderer,state);
ActionModeCombat.Activated=false;CombatPresentation.Before(c.renderer,out state);Check(!state.Applied,"outside combat remains vanilla");
ActionModeCombat.Activated=true;Game.isPaused=true;CombatPresentation.Before(c.renderer,out state);Check(!state.Applied,"mandatory pause remains vanilla");Game.isPaused=false;
c.currentZone=new();CombatPresentation.Before(c.renderer,out state);Check(!state.Applied,"old zone timing cannot leak across transitions");
CombatPresentation.Record(c,.26f,2);c.pos=new(2,1);CombatPresentation.Before(c.renderer,out state);Check(!state.Applied,"unrelated position change cannot reuse stale timing");
CombatPresentation.Record(c,float.NaN,2);CombatPresentation.Before(c.renderer,out state);Check(!state.Applied,"invalid packet timing falls back to vanilla");
CombatPresentation.Record(c,.26f,float.PositiveInfinity);CombatPresentation.Before(c.renderer,out state);Check(!state.Applied,"invalid turbo rejected");
CombatPresentation.Record(c,.26f,2);c.renderer.movePoint=c.pos.Copy();CombatPresentation.Before(c.renderer,out state);Check(!state.Applied,"completed idle renderer untouched");
c.renderer.IsMoving=true;CombatPresentation.Before(c.renderer,out state);Check(state.Applied,"same position retains pace until animation finishes");CombatPresentation.After(c.renderer,state);
CombatPresentation.SnapCorrection(c,new(1,1));Check(c.renderer.Snaps==0,"adjacent moves interpolate");
c.pos=new(7,2);CombatPresentation.Record(c,.26f,2);CombatPresentation.SnapCorrection(c,new(0,0));Check(c.renderer.Snaps==1&&c.renderer.Position==c.pos,"large correction snaps to actual result");
CombatPresentation.Before(c.renderer,out state);Check(!state.Applied,"snap discards prior movement timing");
using var module=ModuleDefinition.ReadModule(args[0]);
var renderer=module.Types.Single(t=>t.Name=="CharaRenderer");var update=renderer.Methods.Single(m=>m.Name=="UpdatePosition");
Check(update.Body.Instructions.Any(i=>i.Operand is FieldReference f&&f.DeclaringType.Name=="Chara"&&f.Name=="actTime"),"installed renderer captures character duration");
Check(update.Body.Instructions.Any(i=>i.Operand is FieldReference f&&f.DeclaringType.Name=="RenderObject"&&f.Name=="gameDelta"),"installed renderer consumes isolated render clock");
var input=module.Types.Single(t=>t.Name=="AM_Adv");var manual=input.Methods.Single(m=>m.Name=="SetManualMove");
Check(manual.Body.Instructions.Any(i=>i.Operand is MethodReference m&&m.Name=="SetTurbo"),"installed SetManualMove resets turbo when starting a new goal");
Console.WriteLine($"{checks} checks passed; rendering boundary simulated and installed native IL inspected.");
