<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><OutputType>Exe</OutputType><TargetFramework>net11.0</TargetFramework><ImplicitUsings>enable</ImplicitUsings><Nullable>enable</Nullable></PropertyGroup><ItemGroup><Compile Include="../../ElinTogether/Models/Delta/Inv/BlendDelta.cs" Link="BlendDelta.cs"/><Compile Include="../../ElinTogether/Patches/Synchronization/BlendPatch.cs" Link="BlendPatch.cs"/></ItemGroup></Project>