using ElinTogether.Models;
using ElinTogether.Net;
using ElinTogether.Patches;
int checks=0;
void Check(bool ok,string why){if(!ok)throw new Exception(why);checks++;}
var host=new ElinNetHost(); var client=new ElinNetClient();
var actor=new Chara{uid=719}; var frey=new Chara{uid=1}; EClass.player.chara=frey;
host.ActiveRemoteCharas[1]=actor; NetSession.Instance.Connection=host;
var potion=new Thing{uid=20,Num=6,parent=actor}; potion.trait=new TraitDrink{owner=potion};
var amulet=new Thing{uid=21,parent=actor,Equipped=true}; CardCache.Add(potion); CardCache.Add(amulet);
BlendRequestDelta Request(Thing? t=null)=>new(){Id=Guid.NewGuid(),ZoneUid=7,Potion=potion,Target=t??amulet};
var request=Request(); request.Apply(host);
Check(potion.Num==5&&amulet.isAcidproof,"one host blend coats target and consumes one potion");
Check(amulet.Equipped&&amulet.parent==actor,"equipped amulet retains equipment and inventory identity");
Check(EClass.pc==frey,"host player context restored");
request.Apply(host); Check(potion.Num==5,"duplicate request does not consume twice");
var result=host.Delta.Items.OfType<BlendResultDelta>().Single();
amulet.isAcidproof=false; result.Apply(client);result.Apply(client);
Check(amulet.isAcidproof&&potion.Num==5,"absolute result applies coating without redoing blend or consuming potion");
amulet.isAcidproof=false; result.Apply(host);Check(!amulet.isAcidproof,"host rejects client-authored result");
NetSession.Instance.Connection=client;
var returned=BlendInputPatch.Before(new InvOwnerBlend(potion),amulet);
Check(!returned&&client.Delta.Items.Last() is BlendRequestDelta&&!amulet.isAcidproof&&potion.Num==5,"client UI requests instead of predicting coating and consumption");
var directCount=client.Delta.Items.Count;
ElinDelta.IsApplying=true;ThingRequest.IsReplayingIntent=true;
BlendInputPatch.Before(new InvOwnerBlend(potion),amulet);
Check(client.Delta.Items.Count==directCount+1,"resumed player drag submits blend despite active delta application");
ThingRequest.IsReplayingIntent=false;
BlendInputPatch.Before(new InvOwnerBlend(potion),amulet);
Check(client.Delta.Items.Count==directCount+1,"actual remote replay cannot submit a blend");
ElinDelta.IsApplying=false;
PlayerControl.LocalInputBlocked=true;var queued=client.Delta.Items.Count;
BlendInputPatch.Before(new InvOwnerBlend(potion),amulet);PlayerControl.LocalInputBlocked=false;
Check(queued==client.Delta.Items.Count,"spectator cannot submit blending input");
NetSession.Instance.Connection=host;
Check(BlendInputPatch.Before(new InvOwnerBlend(potion),amulet),"host UI still runs vanilla blending");
NetSession.Instance.Connection=null;
Check(BlendInputPatch.Before(new InvOwnerBlend(potion),amulet),"solo UI remains native");NetSession.Instance.Connection=host;
var count=potion.Num;host.Accept=false;Request().Apply(host);host.Accept=true;
Check(potion.Num==count,"blocked peer rejected");
var stale=Request();EClass._zone.uid=9;stale.Apply(host);EClass._zone.uid=7;
Check(potion.Num==count,"old-floor request rejected");
potion.parent=frey;Request().Apply(host);potion.parent=actor;
Check(potion.Num==count,"cannot spend another player's potion");
var stranger=new Chara{uid=4,party=new object()};amulet.parent=stranger;Request().Apply(host);amulet.parent=actor;
Check(potion.Num==count,"foreign non-party target rejected");
frey.party=actor.party;amulet.parent=frey;actor.Distance=4;Request().Apply(host);actor.Distance=1;
Check(potion.Num==count,"distant ally target rejected");
Request().Apply(host);Check(potion.Num==count-1&&amulet.isAcidproof,"nearby party ally equipment can be coated");
amulet.parent=actor;amulet.isAcidproof=false;potion.blessedState=BlessedState.Cursed;
Request().Apply(host);Check(amulet.encLV==-1&&!amulet.isAcidproof,"cursed acidproof liquid retains native degradation");
potion.blessedState=BlessedState.Normal;potion.Num=1;Request().Apply(host);
Check(potion.isDestroyed&&potion.Num==0&&amulet.isAcidproof,"last potion consumed while target survives");
potion.isDestroyed=false;potion.Num=4;
var drink=(TraitDrink)potion.trait;drink.Kind=1;potion.blessedState=BlessedState.Blessed;
var food=new Thing{uid=30,parent=actor,Num=3};CardCache.Add(food);host.Delta.Items.Clear();Request(food).Apply(host);
var split=CardCache.All.Values.Single(t=>t.uid>=100);
Check(food.Num==2&&split.Num==1&&split.blessedState==BlessedState.Blessed,"water changes only one item in stack");
var states=host.Delta.Items.OfType<BlendResultDelta>().ToArray();
Check(states.Any(s=>s.Item.Find()==split),"split outcome captured for existing-item result synchronization");
split.blessedState=BlessedState.Normal;foreach(var s in states)s.Apply(client);
Check(split.blessedState==BlessedState.Blessed&&food.blessedState==BlessedState.Normal,"water result updates split item without changing remainder");
drink.Kind=2;host.Delta.Items.Clear();Request(food).Apply(host);
var poisoned=CardCache.All.Values.Single(t=>t.elements.Base(702)>0);
var poisonResult=host.Delta.Items.OfType<BlendResultDelta>().Single(s=>s.Item.Find()==poisoned);
poisoned.elements.SetBase(702,0);poisonResult.Apply(client);poisonResult.Apply(client);
Check(poisoned.elements.Base(702)==5,"poison result is absolute rather than additive on duplicate delivery");
drink.Kind=3;Request(food).Apply(host);Check(CardCache.All.Values.Any(t=>t.elements.Base(703)==5),"love mixture retains native food path");
CharaProgressCompleteEvent.Capturing=true;amulet.isAcidproof=false;drink.Kind=0;potion.Num=2;host.Delta.Items.Clear();Request(amulet).Apply(host);
Check(CharaProgressCompleteEvent.Results.Count>0&&!host.Delta.Items.OfType<BlendResultDelta>().Any(),"AI completion captures blend properties after replay");
Console.WriteLine($"{checks} blending checks passed");
