using ElinTogether.Models;
using ElinTogether.Net;
using ElinTogether.Patches;
using Mono.Cecil;
using HarmonyLib;
using System.Reflection.Emit;
int n=0;void Check(bool b,string s){if(!b)throw new Exception(s);n++;Console.WriteLine("PASS "+s);}
using var native=ModuleDefinition.ReadModule(args[0]);
bool Calls(MethodDefinition method,string name)=>method.Body.Instructions.Any(i=>i.Operand is MethodReference r&&r.Name==name);
var scroll=native.Types.Single(t=>t.Name=="TraitScrollStatic").Methods.Single(m=>m.Name=="OnRead");
Check(Calls(scroll,"ModNum")&&Calls(scroll,"ProcAt"),"native scroll consumption precedes the shared effect path");
Check(scroll.Body.Instructions.First(i=>i.Operand is MethodReference{Name:"ModNum"}).Offset<scroll.Body.Instructions.First(i=>i.Operand is MethodReference{Name:"ProcAt"}).Offset,"effect hook does not consume a second scroll");
Check(Calls(native.Types.Single(t=>t.Name=="Act").Methods.Single(m=>m.Name=="Perform"&&m.Parameters.Count==0),"ProcAt"),"native spell performance reaches the same effect path");
var chara=native.Types.Single(t=>t.Name=="Chara");
var revive=chara.Methods.Single(m=>m.Name=="Revive");
var predicate=chara.NestedTypes.SelectMany(t=>t.Methods).Single(m=>m.HasBody&&m.Body.Instructions.Any(i=>i.Operand is MethodReference{Name:"get_SelfWeight"})&&m.Body.Instructions.Any(i=>i.Operand is MethodReference{Name:"get_WeightLimit"}));
foreach(var name in new[]{"get_IsContainer","get_SelfWeight","get_WeightLimit","get_CanBeDropped","get_c_lockLv"})Check(predicate.Body.Instructions.Any(i=>i.Operand is MethodReference r&&r.Name==name),"native overweight predicate retains "+name);
Check(predicate.Body.Instructions.Any(i=>i.Operand is TypeReference{Name:"TraitChestPractice"}),"native practice-chest exception remains");
var callbacks=native.Types.Single(t=>t.Name=="Scene").NestedTypes.SelectMany(t=>t.Methods).Where(m=>m.HasBody).ToArray();
foreach(var marker in new[]{"pc_revive_town","pc_deathChoice","crawlup"})Check(callbacks.Count(m=>m.Body.Instructions.Any(i=>i.Operand as string==marker))==1,"one native death callback for "+marker);
var getRevived=chara.Methods.Single(m=>m.Name=="GetRevived");
Check(getRevived.Body.Instructions.Count(i=>i.Operand is MethodReference{Name:"get_pc"}&&i.Next?.Operand is FieldReference{Name:"pos"})==1,"one native resurrection location anchor");
var host=new ElinNetHost();NetSession.Instance.Connection=host;var zone=EClass._zone;zone.uid=20;
var owner=EClass.pc=new Chara{uid=1,currentZone=zone,pos=new(){x=4,z=8}};EClass.game.cards.globalCharas[1]=owner;
Thing Item(int id,int weight,Card parent,bool container=false){var t=new Thing{uid=id,SelfWeight=weight,parentCard=parent,IsContainer=container};parent.things.Items.Add(t);return t;}
var tent=Item(10,101,owner);var ordinary=Item(11,100,owner);var box=Item(12,999,owner,true);var nested=Item(13,101,box);var locked=Item(14,999,owner,true);locked.c_lockLv=1;var protectedItem=Item(15,101,locked);var fixedItem=Item(16,101,owner);fixedItem.trait.CanBeDropped=false;
var practice=Item(17,999,owner,true);practice.c_lockLv=1;practice.trait=new TraitChestPractice();var trainingItem=Item(18,101,practice);
var site=PlayerDeathRecovery.Capture(owner);owner.isDead=true;ElinDelta.IsApplying=true;PlayerDeathRecovery.DropOverweight(owner,site);
Check(zone.Ground.Select(t=>t.uid).SequenceEqual(new[]{10,13,18}),"early death drop uses vanilla eligibility including nested and locked inventory");
Check(zone.Ground.All(t=>t.ignoreAutoPick&&t.pos.x==4&&t.pos.z==8)&&zone.Simulated,"drops retain death position, disable auto pickup and use authoritative simulation");
Check(ElinDelta.IsApplying&&owner.things.LastAccessible==false,"drop scope restores replay state and visits inaccessible inventory as vanilla does");ElinDelta.IsApplying=false;
PlayerDeathRecovery.DropOverweight(owner,site);Check(zone.Ground.Count==3,"repeat death recovery cannot clone or redrop moved items");
Check(PlayerDeathRecovery.Capture(owner)==null,"already dead character cannot start another drop");
var remote=new Chara{uid=2,Remote=true,currentZone=zone,c_wasInPcParty=true};host.ActiveRemoteCharas[1]=remote;EClass.game.cards.globalCharas[2]=remote;
owner.isDead=false;var remoteSite=PlayerDeathRecovery.Capture(remote);remote.isDead=true;remote.currentZone=null;PlayerDeathRecovery.DropOverweight(remote,remoteSite);
Check(PlayerDeathRecovery.RescueTarget(owner,owner)==remote,"removed remote-player body is eligible on its recorded death floor");
var otherZone=new Zone{uid=21};EClass._zone=otherZone;owner.currentZone=otherZone;Check(PlayerDeathRecovery.RescueTarget(owner,owner)==null,"same-floor rescue priority excludes distant players, leaving native fallback");EClass._zone=zone;owner.currentZone=zone;
NetSession.Instance.Connection=new ElinNetClient();Check(!PlayerRecoveryPatch.Resurrection(EffectId.Revive,owner,owner,out var noScope)&&noScope==null,"client prediction and replay never choose a resurrection target");
NetSession.Instance.Connection=host;ElinDelta.IsApplying=true;var run=PlayerRecoveryPatch.Resurrection(EffectId.Revive,owner,owner,out var scope);
Check(!run&&!remote.isDead&&remote.Revives==1&&host.Delta.Items.OfType<CharaReviveDelta>().Count()==1,"host resolves remote-player rescue once and publishes outcome during spell replay");
Check(remote.pos.x==owner.pos.x&&remote.IsPCParty,"rescue returns remote player near caster and to party");PlayerRecoveryPatch.EndEffect(scope);Check(ElinDelta.IsApplying,"effect finalizer restores outer replay state");ElinDelta.IsApplying=false;
Check(PlayerRecoveryPatch.Resurrection(EffectId.Revive,owner,owner,out scope),"without dead humans native NPC resurrection selection is retained");PlayerRecoveryPatch.EndEffect(scope);
var npc=new Chara{uid=3,isDead=true};host.Delta.Items.Clear();
PlayerRecoveryPatch.Resurrection(EffectId.Revive,owner,owner,out scope);npc.Revive(owner.pos,true);PlayerRecoveryPatch.EndEffect(scope);
Check(host.Delta.Items.OfType<CharaReviveDelta>().Count()==1,"native NPC resurrection also publishes its chosen result");
Check(PlayerRecoveryPatch.Resurrection(EffectId.Other,owner,owner,out scope)&&scope==null,"other spell effects untouched");
// Client spell revives host without turning the host into the caster.
owner.isDead=true;remote.currentZone=zone;remote.pos=new(){x=9,z=12};host.Delta.Items.Clear();
var dialog=new Dialog();PlayerDeathDialogue.Track("dialogLastword",dialog);EClass.player.deathDialog=true;
PlayerRecoveryPatch.Resurrection(EffectId.Revive,remote,remote,out scope);PlayerRecoveryPatch.EndEffect(scope);
Check(!owner.isDead&&owner.pos.x==9&&host.Delta.Items.Count==1,"client caster rescues host at client location through the same effect route");
Check(dialog.Closed&&!EClass.player.deathDialog&&!PlayerDeathDialogue.StillDead(),"rescue closes only tracked death dialog and invalidates stale native callbacks");
owner.isDead=true;Check(PlayerDeathDialogue.StillDead(),"unrescued player can still choose native crawl-home without a scroll");
// No standalone client request may resurrect someone else's character.
var bad=new CharaReviveDelta{Owner=owner,LastWords=null,Pos=new(){X=1,Z=1}};bad.Apply(host);Check(owner.isDead,"client cannot forge crawl-home for the host");
remote.isDead=true;remote.currentZone=null;var crawl=new CharaReviveDelta{Owner=remote,LastWords="bye",Pos=new(){X=3,Z=4}};crawl.Apply(host);Check(!remote.isDead&&remote.Graves==1,"normal own-character crawl-home request remains supported");
var client=new ElinNetClient();NetSession.Instance.Connection=client;EClass.pc=remote;remote.isDead=true;var beforeRevives=remote.Revives;
var result=new CharaReviveDelta{Owner=remote,LastWords=null,Pos=new(){X=9,Z=12}};result.Apply(client);result.Apply(client);
Check(!remote.isDead&&remote.Revives==beforeRevives+1&&client.Delta.Items.Count==0,"client applies authoritative rescue once without sending another revive request");
var code=PlayerRecoveryPatch.ReviveNearCaster(new[]{new CodeInstruction(OpCodes.Call,AccessTools.PropertyGetter(typeof(EClass),nameof(EClass.pc))),new CodeInstruction(OpCodes.Ldfld,AccessTools.Field(typeof(Card),nameof(Card.pos)))}).ToArray();
Check(code[0].operand.Equals(AccessTools.Method(typeof(PlayerRecoveryPatch),nameof(PlayerRecoveryPatch.ResurrectionOrigin))),"native NPC resurrection location routes to actual caster only");
NetSession.Instance.Connection=null;Check(PlayerDeathRecovery.Capture(remote)==null&&PlayerDeathDialogue.StillDead(),"solo death and dialogue retain vanilla paths");
Console.WriteLine($"{n} checks passed; native metadata checked, game boundaries simulated.");
