<Project Sdk="Microsoft.NET.Sdk">
<PropertyGroup><OutputType>Exe</OutputType><TargetFramework>net11.0</TargetFramework><ImplicitUsings>enable</ImplicitUsings><Nullable>enable</Nullable></PropertyGroup>
<ItemGroup>
<Compile Include="../../ElinTogether/Models/PartyMembership.cs" Link="PartyMembership.cs" />
<Compile Include="../../ElinTogether/Models/PartyBoardManagement.cs" Link="PartyBoardManagement.cs" />
<Compile Include="../../ElinTogether/Models/Delta/Chara/PartyBoardDelta.cs" Link="PartyBoardDelta.cs" />
<Compile Include="../../ElinTogether/Models/Delta/Chara/PartyMemberDelta.cs" Link="PartyMemberDelta.cs" />
<Compile Include="../../ElinTogether/Patches/Synchronization/PartyBoardPatch.cs" Link="PartyBoardPatch.cs" />
<Reference Include="0Harmony"><HintPath>$(ElinGamePath)/BepInEx/core/0Harmony.dll</HintPath></Reference>
<Reference Include="MonoMod.Utils"><HintPath>$(ElinGamePath)/BepInEx/core/MonoMod.Utils.dll</HintPath></Reference>
<Reference Include="MonoMod.RuntimeDetour"><HintPath>$(ElinGamePath)/BepInEx/core/MonoMod.RuntimeDetour.dll</HintPath></Reference>
<Reference Include="Mono.Cecil"><HintPath>$(ElinGamePath)/BepInEx/core/Mono.Cecil.dll</HintPath></Reference>
</ItemGroup></Project>
