<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><OutputType>Exe</OutputType><TargetFramework>net11.0</TargetFramework><ImplicitUsings>enable</ImplicitUsings><Nullable>enable</Nullable></PropertyGroup>
  <ItemGroup>
    <Reference Include="Mono.Cecil"><HintPath>$(ElinGamePath)/BepInEx/core/Mono.Cecil.dll</HintPath></Reference>
    <Compile Include="../../ElinTogether/Models/Delta/Card/CardEnhancementDelta.cs" Link="CardEnhancementDelta.cs" />
    <Compile Include="../../ElinTogether/Patches/DeltaEvents/Card/CardEnhancementEvent.cs" Link="CardEnhancementEvent.cs" />
    <Compile Include="../../ElinTogether/Models/Delta/Card/CardLockStateDelta.cs" Link="CardLockStateDelta.cs" />
    <Compile Include="../../ElinTogether/Patches/DeltaEvents/Card/CardLockStateEvent.cs" Link="CardLockStateEvent.cs" />
  </ItemGroup>
</Project>
