using ElinTogether.Models;
using ElinTogether.Net;
using ElinTogether.Patches;
using Mono.Cecil;

int checks = 0;
void Check(bool condition, string label) { if (!condition) throw new Exception(label); checks++; Console.WriteLine("PASS " + label); }
using var module = ModuleDefinition.ReadModule(args[0]);
MethodDefinition Method(string type, string name) => module.Types.Single(t => t.Name == type).Methods.Single(m => m.Name == name);
bool Calls(MethodDefinition method, string name) => method.Body.Instructions.Any(i => i.Operand is MethodReference m && m.Name == name);
var modify = Method("Card", "ModEncLv");
Check(modify.Parameters.Count == 1 && modify.Parameters[0].ParameterType.FullName == "System.Int32", "installed native enhancement mutation has supported signature");
Check(Calls(Method("TraitCrafter", "Craft"), "ModEncLv"), "installed crafter repairs call shared enhancement method");
Check(Calls(Method("Card", "SetEncLv"), "ModEncLv"), "installed absolute setter delegates to native enhancement mutation");
Check(Calls(modify, "ApplyMaterialElements") && Calls(modify, "ModBase"), "native mutation refreshes material bonuses and equipment elements");
Check(Calls(Method("Thing", "ApplyMaterialElements"), "SetParent"), "native material refresh updates equipped character links");

var host = new ElinNetHost(); var client = new ElinNetClient();
var hostGear = new Thing { uid = 29300, encLV = -2, Armor = -3 };
CardCache.Items[hostGear.uid] = hostGear; NetSession.Instance.Connection = host;
CharaProgressCompleteEvent.Active = true;
hostGear.ModEncLv(1); hostGear.ModEncLv(1);
Check(hostGear.encLV == 0 && CharaProgressCompleteEvent.Packed.Count == 2 && host.Delta.Items.Count == 0, "two repairs publish host levels inside existing completion bundle");
Check(CharaProgressCompleteEvent.Packed.Cast<CardEnhancementDelta>().Select(d => d.Level).SequenceEqual(new[] { -1, 0 }), "packets contain absolute levels, not another repair command");
var cached = new Thing { uid = 29300, encLV = -2, Armor = -3, Equipped = true, LinkedArmor = -3 };
var owner = new Card { uid = 719 }; cached.parent = owner;
CardCache.Items[cached.uid] = cached; NetSession.Instance.Connection = client;
foreach (var result in CharaProgressCompleteEvent.Packed) result.Apply(client);
Check(cached.encLV == 0 && cached.Armor == 1 && cached.LinkedArmor == 1, "cached equipped girdle receives repaired level and native linked armor changes");
Check(cached.MaterialRefreshes == 4 && cached.NativeCalls == 2, "both repair steps invoke native material recalculation");
Check(ReferenceEquals(CardCache.Items[29300], cached) && cached.parent == owner, "repair preserves cached identity, ownership and equipment references");
var final = CharaProgressCompleteEvent.Packed.Last(); final.Apply(client); final.Apply(client);
Check(cached.NativeCalls == 2 && cached.Armor == 1, "repeated final state cannot double-enchant item");
Check(client.Delta.Items.Count == 0 && LayerInventory.Dirty.Contains(29300), "client refreshes inventory without echoing gameplay");
cached.ModEncLv(-1); var prior = cached.encLV; final.Apply(host);
Check(cached.encLV == prior, "host ignores incoming enhancement result");
cached.isDestroyed = true; final.Apply(client); Check(cached.encLV == prior, "destroyed item stays untouched"); cached.isDestroyed = false;
CardCache.Items.Remove(cached.uid); final.Apply(client); Check(CardCache.Items.Count == 0, "missing item is not recreated from an enhancement packet");

NetSession.Instance.Connection = host; CardCache.Items[hostGear.uid] = hostGear;
CharaProgressCompleteEvent.Active = false; host.Delta.Items.Clear();
owner.AddThing(hostGear, false, -1, -1);
Check(host.Delta.Items.Count == 1 && ((CardEnhancementDelta)host.Delta.Items[0]).Level == 0, "transfer republishes current enhancement for previously repaired gear");
var shoes = new Thing { uid = 40047, encLV = -1, Armor = -2 };
CardCache.Items[shoes.uid] = shoes; shoes.ModEncLv(1);
Check(((CardEnhancementDelta)host.Delta.Items.Last()).Card.Uid == 40047, "non-bundled enhancement uses normal host result queue");
NetSession.Instance.Connection = client; CardCache.Items[hostGear.uid] = cached;
host.Delta.Items[0].Apply(client);
Check(cached.encLV == 0, "retransfer repairs stale pre-fix cached enhancement without reconnect");
var weapon = new Thing { uid = 99, encLV = 2, Damage = 4, IsWeapon = true };
CardCache.Items[99] = weapon;
new CardEnhancementDelta { Card = weapon, Level = 1 }.Apply(client);
Check(weapon.encLV == 1 && weapon.Damage == 3, "authoritative downgrade repairs client weapon prediction using native damage adjustment");

NetSession.Instance.Connection = host; var count = host.Delta.Items.Count;
shoes.ModEncLv(0); Check(host.Delta.Items.Count == count, "no-change mutation sends nothing");
EClass.game.isLoading = true; shoes.ModEncLv(1); EClass.game.isLoading = false;
Check(host.Delta.Items.Count == count, "save loading does not generate enhancement traffic");
var uncached = new Thing { uid = 7 }; uncached.ModEncLv(1);
var food = new Thing { uid = 8, IsEquipmentOrRangedOrAmmo = false }; CardCache.Items[8] = food; food.ModEncLv(1);
Check(host.Delta.Items.Count == count, "generation and unrelated food enhancement remain outside equipment synchronization");
NetSession.Instance.Connection = null; shoes.ModEncLv(1);
Check(host.Delta.Items.Count == count, "solo play stays native");
Console.WriteLine($"{checks} equipment checks passed; installed native IL inspected, Unity rendering simulated.");

// Lock changes happen before the completion callback, so they need their own result.
var unlock=Method("Trait","OnLockOpen");
Check(new[]{"set_c_lockLv","set_c_lockedHard","set_c_priceAdd","set_isLostProperty"}.All(n=>Calls(unlock,n)),"installed unlock mutates all four synchronized lock fields");
Check(Calls(unlock,"ModKarma")&&Calls(unlock,"GetAchievement"),"native unlock has gameplay effects that clients must not replay");
Check(Calls(Method("Trait","TryOpenLock"),"OnLockOpen")&&Calls(Method("Trait","TryPryOpenLock"),"OnLockOpen"),"picking and prying share the same native unlock boundary");
IEnumerable<TypeDefinition> AllTypes(TypeDefinition t)=>new[]{t}.Concat(t.NestedTypes.SelectMany(AllTypes));
var lockCallbacks=AllTypes(module.Types.Single(t=>t.Name=="AI_OpenLock")).SelectMany(t=>t.Methods).Where(m=>m.HasBody).ToArray();
Check(lockCallbacks.Any(m=>Calls(m,"TryOpenLock")&&Calls(m,"CompleteProgress")),"installed lock roll runs in the progress tick before completion");
Check(Calls(Method("TraitChestPractice","OnSimulateHour"),"set_c_lockLv"),"practice chest relocks through hourly native simulation");
var chest=new Thing{uid=505,c_lockLv=12,c_lockedHard=true,c_priceAdd=900,isLostProperty=true,LV=7};
var chestTrait=new Trait{owner=chest};chest.trait=chestTrait;CardCache.Items[chest.uid]=chest;
NetSession.Instance.Connection=host;host.Delta.Items.Clear();CharaProgressCompleteEvent.Active=false;
chestTrait.OnLockOpen();
Check(host.Delta.Items.Count==1&&chestTrait.UnlockCalls==1,"host unlock publishes immediately outside completion capture");
var unlocked=(CardLockStateDelta)host.Delta.Items.Single();
Check(unlocked.LockLevel==0&&!unlocked.HardLock&&unlocked.PriceAdjustment==0&&!unlocked.LostProperty,"snapshot captures final metadata after native cleanup");
chest.c_lockLv=12;chest.c_lockedHard=true;chest.c_priceAdd=900;chest.isLostProperty=true;
NetSession.Instance.Connection=client;unlocked.Apply(client);unlocked.Apply(client);
Check(chest.c_lockLv==0&&!chest.c_lockedHard&&chest.c_priceAdd==0&&!chest.isLostProperty,"client updates existing cached chest including hard-lock and lost-property state");
Check(chestTrait.UnlockCalls==1&&client.Delta.Items.Count==0,"duplicate result never repeats native unlock effects or sends a request");
Check(LayerInventory.Dirty.Contains(chest.uid),"open inventory is refreshed after unlocking");
chest.c_lockLv=4;unlocked.Apply(host);Check(chest.c_lockLv==4,"host rejects client-supplied lock results");
chest.isDestroyed=true;unlocked.Apply(client);Check(chest.c_lockLv==4,"pried-open destroyed chest is never revived");chest.isDestroyed=false;
CardCache.Items.Remove(chest.uid);unlocked.Apply(client);Check(!CardCache.Items.ContainsKey(chest.uid),"unloaded chest is not recreated from an unlock result");CardCache.Items[chest.uid]=chest;
NetSession.Instance.Connection=host;CharaProgressCompleteEvent.Active=true;CharaProgressCompleteEvent.Packed.Clear();host.Delta.Items.Clear();
chest.c_lockedHard=false;chest.c_priceAdd=123;chestTrait.OnLockOpen();
Check(CharaProgressCompleteEvent.Packed.Single() is CardLockStateDelta{PriceAdjustment:123}&&host.Delta.Items.Count==0,"nested unlock uses existing completion bundle and preserves ordinary price adjustment");
CharaProgressCompleteEvent.Active=false;
var practice=new TraitChestPractice{owner=chest};chest.trait=practice;chest.c_lockLv=0;chest.LV=7;
CardLockStateEvent.BeforeReset(practice,out var oldLock);chest.LV=8;chest.c_lockLv=8;CardLockStateEvent.AfterReset(practice,oldLock);
var reset=(CardLockStateDelta)host.Delta.Items.Single();chest.c_lockLv=0;chest.LV=7;NetSession.Instance.Connection=client;reset.Apply(client);
Check(chest.c_lockLv==8&&chest.LV==8,"client sees practice relock and new practice level");
NetSession.Instance.Connection=host;host.Delta.Items.Clear();CardLockStateEvent.BeforeReset(practice,out oldLock);CardLockStateEvent.AfterReset(practice,oldLock);
Check(host.Delta.Items.Count==0,"unchanged practice hour emits nothing");
NetSession.Instance.Connection=client;CardLockStateEvent.Unlocked(chestTrait);Check(client.Delta.Items.Count==0,"client replay cannot publish authoritative unlocks");
NetSession.Instance.Connection=host;EClass.game.isLoading=true;CardLockStateEvent.Unlocked(chestTrait);EClass.game.isLoading=false;
Check(host.Delta.Items.Count==0,"save loading emits no lock packets");
NetSession.Instance.Connection=null;CardLockStateEvent.Unlocked(chestTrait);Check(host.Delta.Items.Count==0,"solo lock behavior remains native");
Console.WriteLine($"{checks} total equipment/lock checks passed; installed native IL inspected, Unity rendering simulated.");
