<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><OutputType>Exe</OutputType><TargetFramework>net11.0</TargetFramework><ImplicitUsings>enable</ImplicitUsings><Nullable>enable</Nullable></PropertyGroup>
  <ItemGroup><Compile Include="../../ElinTogether/Models/Delta/Inv/CodexRequestDelta.cs" Link="CodexRequestDelta.cs" /><Compile Include="../../ElinTogether/Patches/Synchronization/PersonalMsgSayPatch.cs" Link="PersonalMsgSayPatch.cs" /><Compile Include="../../ElinTogether/Models/Delta/Inv/CodexCountDelta.cs" Link="CodexCountDelta.cs" /><Compile Include="../../ElinTogether/Patches/DeltaEvents/Inventory/CodexEvents.cs" Link="CodexEvents.cs" /></ItemGroup>
<ItemGroup><Compile Include="../../ElinTogether/Patches/DeltaEvents/Task/TalismanCraftPatch.cs" Link="TalismanCraftPatch.cs" /><Compile Include="../../ElinTogether/Models/Delta/Card/CardAmmoDelta.cs" Link="CardAmmoDelta.cs" /></ItemGroup></Project>
