using ElinTogether.Models;
using ElinTogether.Net;
int checks = 0;
void Check(bool pass, string name) { if (!pass) throw new Exception(name); Console.WriteLine("PASS " + name); checks++; }
var host = new ElinNetHost(); NetSession.Instance.Connection = host;
var actor = new Chara { uid = 1 }; var merchant = new Chara { uid = 2 }; var chest = new Thing { uid = 3, id = "chest_merchant" }; merchant.AddThing(chest);
var hostActor = EClass.pc;
host.ActiveRemoteCharas[1] = actor;
foreach (var c in new Card[] { actor, merchant, chest }) CardCache.Map[c.uid] = c;
Thing Item(string id, int n, bool stolen = false) {
 var t = new Thing { uid = CardCache.Next++, id = id, Num = n, isStolen = stolen }; CardCache.Map[t.uid] = t; return t;
}
Guid session = Guid.NewGuid();
ShopTradeDelta Trade(Thing item, int num, bool sell, int price) => new() { SessionId = session, RequestId = Guid.NewGuid(), Merchant = merchant, Item = item,
 Quantity = num, Sell = sell, Price = price, ZoneUid = 7, Currency = merchant.trait.CurrencyType, PriceType = merchant.trait.PriceType, OriginPeer = 1, Destination = sell ? chest : actor };
void Close() => new ShopTradeDelta { SessionId = session, Close = true, OriginPeer = 1 }.Apply(host);
var stolen = Item("gem", 5, true); stolen.DeliveryZone = 99; actor.AddThing(stolen);
var sale = Trade(stolen, 5, true, 200); sale.Apply(host); sale.Apply(host);
Check(stolen.DeliveryZone == 0, "sale clears prior delivery tag like native transaction");
Check(actor.Money == 10200 && actor.Charges == 1 && stolen.parent == chest && ShopTrade.Read(actor)!.Sold.Single().Num == 5, "sale transfers and pays once with host-owned ledger");
var buyback = Trade(stolen, 2, false, 80); buyback.Apply(host);
Check(actor.Money == 10120 && ShopTrade.Read(actor)!.Sold.Single().Num == 3 && ShopTrade.Read(actor)!.Bought.Count == 0, "partial buyback uses native sale price and removes only returned quantity");
Close(); Close();
Check(Guild.Thief.Credit == 9 && !stolen.isStolen && ShopTrade.Read(actor) is null && OwnerProgressionAwards.Awards.Count == 0, "net stolen sale settles once and buyback earns no purchase XP");
Trade(stolen, 1, false, 100).Apply(host);
Check(host.Replies[^1].Error is not null, "closed session rejects late trade");
session = Guid.NewGuid();
var unknown = Item("unknown", 1, true); unknown.IsIdentified = false; actor.AddThing(unknown);
Trade(unknown, 1, true, 40).Apply(host); Close();
Check(unknown.IsIdentified && unknown.isStolen && Guild.Thief.Credit == 9, "unidentified sale preserves vanilla exclusion from stolen-sale credit");
session = Guid.NewGuid();
var purchase = Item("deed", 2); chest.AddThing(purchase);
Trade(purchase, 2, false, 200).Apply(host); Close();
Check(EClass.player.flags.landDeedBought == 2 && OwnerProgressionAwards.Awards.Single().amount == 44 &&
 OwnerProgressionAwards.Awards.Single().actor == actor && hostActor.Experience == 0,
 "purchases update shared world counter and queue owner Negotiation XP without host reroll");
session = Guid.NewGuid();
var item = Item("a", 3, true); actor.AddThing(item);
var before = actor.Money;
Trade(item, 1, true, 41).Apply(host);
Check(host.Replies[^1].Error is not null && actor.Money == before && item.Num == 3, "stale quote rejected before split or payment");
var forged = Trade(item, 4, true, 160); forged.Apply(host);
Check(host.Replies[^1].Error is not null && item.Num == 3, "invalid quantity rejected");
var outsider = new Chara { uid = 9 }; outsider.AddThing(item);
Trade(item, 1, true, 40).Apply(host);
Check(host.Replies[^1].Error is not null && actor.Money == before, "another player's goods cannot be sold");
actor.AddThing(item); actor.Distance = 10; Trade(item, 1, true, 40).Apply(host); actor.Distance = 1;
Check(host.Replies[^1].Error is not null, "distant merchant rejected");
var wrong = Trade(item, 1, true, 40); wrong.Currency = CurrencyType.Casino_coin; wrong.Apply(host);
Check(host.Replies[^1].Error is not null, "client cannot choose merchant currency");
item.parent!.things.Remove(item); item.parent = null; ThingRequest.Dangling[(item.uid,1)] = actor;
Trade(item, 1, true, 40).Apply(host);
Check(host.Replies[^1].Error is null && actor.Money == before + 40, "validated player's dangling drag can complete a sale");
ShopTrade.Reset();
Check(ShopTrade.Read(actor)!.Sold.Single().Num == 1, "ledger persists across transient session reset through real JSON");
ShopTrade.Release(actor); ShopTrade.Release(actor);
Check(Guild.Thief.Credit == 12, "disconnect settles saved ledger exactly once");
session = Guid.NewGuid(); merchant.trait.CurrencyType = CurrencyType.Casino_coin;
var tokenItem = Item("prize", 1, true); chest.AddThing(tokenItem);
Trade(tokenItem, 1, false, 100).Apply(host); Close();
Check(!tokenItem.isStolen && OwnerProgressionAwards.Awards.Count == 1 && Guild.Thief.Credit == 12, "non-money purchases clear stolen flag without Money-only rewards");
// Separate players at one merchant have independent native ledgers.
merchant.trait.CurrencyType = CurrencyType.Money;
var secondActor = new Chara { uid = 10 }; host.ActiveRemoteCharas[2] = secondActor; CardCache.Map[10] = secondActor;
session = Guid.NewGuid();
var firstGem = Item("gem", 1, true); actor.AddThing(firstGem); Trade(firstGem, 1, true, 40).Apply(host);
var secondGem = Item("gem", 1, true); secondActor.AddThing(secondGem);
var secondTrade = Trade(secondGem, 1, true, 40); secondTrade.OriginPeer = 2; secondTrade.SessionId = Guid.NewGuid(); secondTrade.Apply(host);
var beforeCredit = Guild.Thief.Credit; Close();
Check(Guild.Thief.Credit == beforeCredit + 3 && ShopTrade.Read(secondActor)!.Sold.Single().Num == 1 && chest.c_lockLv == 0,
 "closing first player preserves second player's ledger and open merchant chest");
new ShopTradeDelta { SessionId = secondTrade.SessionId, Close = true, OriginPeer = 2 }.Apply(host);
Check(Guild.Thief.Credit == beforeCredit + 6 && chest.c_lockLv == 1, "last shop session settles independently and relocks chest");
session = Guid.NewGuid();
var refundable = Item("refundable", 3); chest.AddThing(refundable);
Trade(refundable, 3, false, 300).Apply(host);
Trade(refundable, 3, true, 300).Apply(host);
var awardsBefore = OwnerProgressionAwards.Awards.Count; Close();
Check(OwnerProgressionAwards.Awards.Count == awardsBefore, "full purchase refund leaves no Negotiation XP");
session = Guid.NewGuid(); actor.Discount = 10;
var priced = Item("priced", 1); chest.AddThing(priced); Trade(priced, 1, false, 90).Apply(host);
Check(host.Replies[^1].Error is null && EClass.pc == hostActor, "native quote and netting use buyer stats and restore host context");
actor.Discount = 0; Close();
session = Guid.NewGuid();
var equipment = Item("axe", 1); equipment.isEquipped = true; equipment.blessedState = BlessedState.Cursed; actor.AddThing(equipment);
Trade(equipment, 1, true, 40).Apply(host);
Check(host.Replies[^1].Error is not null && equipment.isEquipped, "cursed equipment cannot be sold");
equipment.blessedState = BlessedState.Normal; Trade(equipment, 1, true, 40).Apply(host);
Check(host.Replies[^1].Error is null && !equipment.isEquipped, "uncursed equipped item is unequipped by host before sale"); Close();
// Boundary tests for asynchronous inventory completion and close ordering.
var client = new ElinNetClient(); NetSession.Instance.Connection = client; EClass.game.player.chara = actor;
var nativeShop = new ShopTransaction { trader = new InvOwnerShop(merchant, chest, CurrencyType.Money, PriceType.Default) };
ShopTransaction.current = nativeShop;
var uiTransaction = new InvOwner.Transaction { thing = priced, num = 1, destInv = new InvOwnerShop(actor, actor, CurrencyType.None, PriceType.Default), Quote = 100 };
Check(ShopTrade.Submit(uiTransaction, false) && ShopTrade.Submit(uiTransaction, false) && client.Delta.Sent.Count == 1,
 "one pending trade blocks duplicate UI submission");
var uiRequest = (ShopTradeDelta)client.Delta.Sent.Single();
Check(ShopTrade.CloseClient(nativeShop) && client.Delta.Sent.Count == 1, "closing UI waits for pending trade reply before sending settlement");
new ShopTradeReplyDelta { RequestId = uiRequest.RequestId, Item = priced, Ledger = LZ4Bytes.Create(new ShopTradeLedger()) }.Apply(client);
Check(client.Delta.Sent.Count == 2 && ((ShopTradeDelta)client.Delta.Sent[^1]).Close && uiTransaction.ProcessCalls == 0,
 "late reply settles once without reopening or executing closed UI");
var replay = new InvOwner.Transaction(); ShopTrade.Replaying = replay;
bool free = false; ElinTogether.Patches.ShopTradePatch.FreeTrade(replay, ref free);
bool valid = false; var runValidation = ElinTogether.Patches.ShopTradePatch.IsValid(replay, ref valid);
Check(free && valid && !runValidation, "approved drag presentation skips native payment and stale local validation");
ShopTrade.Replaying = null;
free = false; ElinTogether.Patches.ShopTradePatch.FreeTrade(replay, ref free);
Check(!free && ElinTogether.Patches.ShopTradePatch.IsValid(replay, ref valid), "ordinary transactions retain native validation and payment behavior");
ShopTrade.FinishingDrag = true; bool done = false;
Check(!ElinTogether.Patches.ShopTradePatch.FinishPaidDrag(ref done) && done, "native drag cleanup cannot execute paid transfer a second time");
ShopTrade.Reset();
Check(!ShopTrade.FinishingDrag && ShopTrade.Replaying is null, "session reset clears presentation scopes");
NetSession.Instance.Connection = host; EClass.game.player.chara = hostActor;
session = Guid.NewGuid();
var offMap = Item("offmap", 1, true); actor.AddThing(offMap); Trade(offMap, 1, true, 40).Apply(host);
CardCache.Map.Remove(offMap.uid);
Close();
Check(!CardCache.Map.ContainsKey(offMap.uid) && offMap.isStolen, "settling archived ledger never respawns a missing world item");
CardCache.Map[offMap.uid] = offMap; ShopTrade.ApplyPendingFlags();
Check(!offMap.isStolen, "saved flag update reaches real item when it becomes available");
session = Guid.NewGuid();
var noRoom = Item("noroom", 1); chest.AddThing(noRoom); actor.things.Full = true;
var funds = actor.Money; Trade(noRoom, 1, false, 100).Apply(host); actor.things.Full = false;
Check(host.Replies[^1].Error is not null && actor.Money == funds && noRoom.parent == chest, "full destination rejects before charging or removing stock");
session = Guid.NewGuid(); actor.Money = 0; Trade(noRoom, 1, false, 100).Apply(host);
Check(host.Replies[^1].Error is not null && noRoom.parent == chest, "insufficient funds leave stock untouched");
NetSession.Instance.Connection = client; EClass.game.player.chara = actor;
var empty = new ShopTransaction { trader = nativeShop.trader }; ShopTransaction.current = empty;
var count = client.Delta.Sent.Count;
ShopTrade.CloseClient(empty);
Check(client.Delta.Sent.Count == count + 1 && ((ShopTradeDelta)client.Delta.Sent[^1]).Close, "empty shop close still requests chest cleanup");

// Host reservation and cursor presentation must remain distinct in both orders.
var paid = Item("paidrod", 1); actor.AddThing(paid);
var paidTransaction = new InvOwner.Transaction { thing = paid, destInv = new InvOwnerShop(actor, actor, CurrencyType.None, PriceType.Default) };
ShopTrade.Replaying = paidTransaction;
var cursor = new DragItemCard(); cursor.from.thing = paid; EClass.ui.currentDrag = cursor;
ElinTogether.Patches.ShopTradePatch.StartPaidDrag(cursor);
Check(paid.parent is null && !actor.things.Contains(paid), "paid cursor detaches from actual buyer inventory rather than original merchant button");
ShopTrade.Replaying = null;
actor.AddThing(paid); ShopTrade.DetachPaidDrag(paid, actor);
Check(paid.parent is null && !actor.things.Contains(paid), "late host reservation cannot recreate a second visible inventory entry");
var unrelated = Item("other", 1); actor.AddThing(unrelated); ShopTrade.DetachPaidDrag(unrelated, actor);
Check(unrelated.parent == actor, "unrelated inventory update is preserved during paid drag");
chest.AddThing(paid); ShopTrade.DetachPaidDrag(paid, chest);
Check(paid.parent == chest, "authoritative transfer to a different container is not detached");
ElinTogether.Patches.ShopTradePatch.EndPaidDrag(cursor); EClass.ui.currentDrag = null;
actor.AddThing(paid); ShopTrade.DetachPaidDrag(paid, actor);
Check(paid.parent == actor, "ending the cursor restores normal authoritative inventory landing");
actor.RemoveCard(paid); EClass.ui.currentDrag = cursor; ShopTrade.Replaying = paidTransaction;
ElinTogether.Patches.ShopTradePatch.StartPaidDrag(cursor); ShopTrade.Replaying = null;
actor.AddThing(paid); ShopTrade.DetachPaidDrag(paid, actor);
Check(paid.parent is null, "reply before reservation still registers the paid cursor");
ShopTrade.Reset(); actor.AddThing(paid); ShopTrade.DetachPaidDrag(paid, actor);
Check(paid.parent == actor, "disconnect/reset discards transient cursor reservation view");
ShopTrade.Replaying = null; ElinTogether.Patches.ShopTradePatch.StartPaidDrag(cursor);
Check(paid.parent == actor, "ordinary native drag is not intercepted");
Console.WriteLine($"{checks} checks passed using vanilla ShopTransaction");
