using ElinTogether.Models;
using ElinTogether.Net;
using ElinTogether.Patches;
using HarmonyLib;
using Mono.Cecil;
using System.Reflection.Emit;
int count=0;
void Check(bool ok,string text){if(!ok)throw new Exception(text);count++;Console.WriteLine("PASS "+text);}
using var module=ModuleDefinition.ReadModule(args[0]);
IEnumerable<TypeDefinition> Types(TypeDefinition t)=>new[]{t}.Concat(t.NestedTypes.SelectMany(Types));
var reserve=module.Types.Single(t=>t.Name=="ListPeopleCallReserve");
var callbacks=Types(reserve).SelectMany(t=>t.Methods).Where(m=>m.HasBody&&m.Body.Instructions.Any(i=>i.Operand is MethodReference r&&r.DeclaringType.Name=="Faction"&&r.Name=="RemoveReserve")).ToArray();
Check(callbacks.Length==1,"installed Elin has exactly one confirmed reserve-release callback");
Check(callbacks[0].Body.Instructions.Count(i=>i.Operand is MethodReference r&&r.Name=="OnBanish")==1,"release performs one native banishment after reserve removal");
Check(reserve.Methods.Single(m=>m.Name=="OnClick").Body.Instructions.Any(i=>i.Operand is MethodReference r&&r.DeclaringType.Name=="FactionBranch"&&r.Name=="Recruit"),"installed hearthstone recruits through native branch method");
var calls=new[]{new CodeInstruction(OpCodes.Callvirt,AccessTools.Method(typeof(Faction),nameof(Faction.RemoveReserve))),new CodeInstruction(OpCodes.Callvirt,AccessTools.Method(typeof(Chara),nameof(Chara.OnBanish)))};
var label=new DynamicMethod("label",typeof(void),Type.EmptyTypes).GetILGenerator().DefineLabel();calls[0].labels.Add(label);
var routed=ReserveReleasePatch.Transpile(calls).ToArray();
Check(routed.All(i=>i.opcode==OpCodes.Call)&&routed[0].labels.Contains(label),"release transpiler preserves stack shape and labels");
bool failed=false;try{ReserveReleasePatch.Transpile([]).ToArray();}catch(InvalidOperationException){failed=true;}
Check(failed,"unsupported release shape fails explicitly");

var branch=new FactionBranch{owner=EClass._zone};EClass._zone.branch=branch;EClass.Home.branches.Add(branch);
EClass.game.spatials.zones[7]=EClass._zone;EClass.game.factions.dictAll["home"]=EClass.Home;
var hostActor=new Chara{uid=1,IsPlayer=true,currentZone=EClass._zone};
var actor=new Chara{uid=2,IsPlayer=true,currentZone=EClass._zone};EClass.player.chara=hostActor;
var host=new ElinNetHost();host.ActiveRemoteCharas[1]=actor;NetSession.Instance.Connection=host;
var npc=new Chara{uid=3,isRestrained=true};EClass.Home.listReserve.Add(new(){chara=npc,isNew=true,deadline=123});
void Command(ReserveOperation op,int zone=7)=>new ReserveCommandDelta{MemberUid=3,ZoneUid=zone,Operation=op}.Apply(host);
Command(ReserveOperation.Refresh);Check(host.Sent.Last() is ReserveStateDelta{Entries.Length:1},"opening receives authoritative reserves including off-map NPC");
Command(ReserveOperation.Recruit,8);Check(branch.Recruits==0,"wrong-zone requests rejected");
npc.Remote=true;Command(ReserveOperation.Release);Check(npc.Banishes==0,"saved human characters protected");npc.Remote=false;
npc.trait.CanBeBanished=false;Command(ReserveOperation.Release);Check(npc.Banishes==0,"native banishment restriction enforced");npc.trait.CanBeBanished=true;
host.Accept=false;Command(ReserveOperation.Recruit);Check(branch.Recruits==0,"blocked peer cannot recruit");host.Accept=true;
branch.Throw=true;try{Command(ReserveOperation.Recruit);}catch(InvalidOperationException){}
Check(EClass.pc==hostActor,"actor context restored after native exception");branch.Throw=false;
Command(ReserveOperation.Recruit);
Check(branch.Recruits==1&&branch.members.Contains(npc)&&npc.homeZone==EClass._zone&&!npc.isRestrained,"client uses native settlement recruitment");
Check(EClass.pc==hostActor,"actor restored after successful recruitment");
Check(host.Delta.Sent.Count==1,"native reserve mutation publishes one final result");
var result=(ReserveStateDelta)host.Delta.Sent.Single();result.Refresh();
Check(result.Entries.Length==0&&result.BranchUid==7&&result.ZoneUid==7,"capture waits for completed native residency and placement");
Command(ReserveOperation.Recruit);Check(branch.Recruits==1,"duplicate recruit cannot recruit twice");
// Recreate the client's pre-request state on the same identity.
branch.members.Clear();npc.homeZone=null;npc.currentZone=null;npc.parent=null;npc.IsGlobal=false;npc.isRestrained=true;
EClass.Home.listReserve.Add(new(){chara=npc});
var client=new ElinNetClient();NetSession.Instance.Connection=client;
var ui=new ListPeopleCallReserve();ReserveManagement.OpenList=new(ui);
result.Apply(client);
Check(EClass.Home.listReserve.Count==0&&branch.members.Single()==npc&&npc.parent==EClass._zone&&npc.IsGlobal&&!npc.isRestrained,"result updates original client NPC without cloning or replaying recruitment");
Check(branch.Recruits==1&&ui.list.Refreshes==1,"client refreshes open reserve UI without native recruit side effects");
result.Apply(client);Check(branch.members.Count==1,"duplicate results do not duplicate residents");
Check(EClass.Home.charaElements.Adds==1,"global equipment contributions applied once on branch entry");
int queued=client.Delta.Sent.Count;
Check(!ReserveManagementPatch.Recruit(npc)&&client.Delta.Sent.Count==queued+1,"client recruit UI sends intent only");
EClass.Home.listReserve.Add(new(){chara=npc});
ReserveReleasePatch.Remove(EClass.Home,npc);ReserveReleasePatch.Banish(npc);
Check(EClass.Home.listReserve.Count==1&&npc.Banishes==0,"client release confirmation cannot remove or banish speculatively");
Check(client.Delta.Sent.Last() is ReserveCommandDelta{Operation:ReserveOperation.Release},"release request routed");
NetSession.Instance.Connection=host;host.Delta.Sent.Clear();Command(ReserveOperation.Release);
Check(npc.Banishes==1&&EClass.Home.listReserve.Count==0,"host executes native release once");
Command(ReserveOperation.Release);Check(npc.Banishes==1,"duplicate release cannot repeat artifacts or banishment");
var release=(ReserveStateDelta)host.Delta.Sent.Single();release.Refresh();Check(release.ZoneUid==0,"release captures final location instead of pre-banish map");
int before=host.Delta.Sent.Count;EClass.Home.AddReserve(npc);Check(host.Delta.Sent.Count==before+1,"host reserve additions are broadcast too");
NetSession.Instance.Connection=null;Check(ReserveManagementPatch.Recruit(npc),"solo recruit keeps vanilla path");
ReserveReleasePatch.Remove(EClass.Home,npc);ReserveReleasePatch.Banish(npc);Check(npc.Banishes==2&&EClass.Home.listReserve.Count==0,"solo confirmed release remains native");
Console.WriteLine($"{count} hearthstone checks passed");

var people=module.Types.Single(t=>t.Name=="BaseListPeople");
var storeCallbacks=Types(people).SelectMany(t=>t.Methods).Where(m=>m.HasBody&&m.Body.Instructions.Any(i=>i.Operand is MethodReference r&&r.DeclaringType.Name=="Faction"&&r.Name=="AddReserve")).ToArray();
Check(storeCallbacks.Length==1,"installed resident UI has one send-to-reserve callback");
Check(storeCallbacks[0].Body.Instructions.Any(i=>i.Operand is MethodReference r&&r.Name=="GetMaxReserve"),"native callback enforces reserve capacity");
var storeCall=new CodeInstruction(OpCodes.Callvirt,AccessTools.Method(typeof(Faction),nameof(Faction.AddReserve)));storeCall.labels.Add(label);
var stored=ReserveStorePatch.Transpile([storeCall]).Single();
Check(stored.opcode==OpCodes.Call&&stored.labels.Contains(label),"store wrapper preserves stack and labels");
failed=false;try{ReserveStorePatch.Transpile([]).ToArray();}catch(InvalidOperationException){failed=true;}
Check(failed,"changed store callback fails explicitly");
EClass.Home.listReserve.Clear();branch.members.Clear();branch.members.Add(npc);npc.faction=EClass.Home;EClass._zone.AddCard(npc,8,9);
NetSession.Instance.Connection=client;
ReserveStorePatch.Store(EClass.Home,npc);
Check(EClass.Home.listReserve.Count==0&&npc.parent==EClass._zone&&branch.members.Contains(npc),"client store does not speculatively remove resident");
Check(client.Delta.Sent.Last() is ReserveCommandDelta{Operation:ReserveOperation.Store},"client store uses existing reserve request protocol");
NetSession.Instance.Connection=host;
EClass.Home.Capacity=0;Command(ReserveOperation.Store);Check(EClass.Home.listReserve.Count==0,"host rechecks capacity");EClass.Home.Capacity=10;
npc.Dead=true;Command(ReserveOperation.Store);Check(EClass.Home.listReserve.Count==0,"dead residents rejected");npc.Dead=false;
npc.Guest=true;Command(ReserveOperation.Store);Check(EClass.Home.listReserve.Count==0,"guests rejected");npc.Guest=false;
npc.currentZone=null;Command(ReserveOperation.Store);Check(EClass.Home.listReserve.Count==0,"off-map residents rejected");npc.currentZone=EClass._zone;
npc.Remote=true;Command(ReserveOperation.Store);Check(EClass.Home.listReserve.Count==0,"saved player cannot be stored");npc.Remote=false;
var party=new Party();party.members.Add(npc);npc.party=party;npc.memberType=FactionMemberType.Livestock;
host.Delta.Sent.Clear();Command(ReserveOperation.Store);
Check(EClass.Home.listReserve.Single().chara==npc&&npc.parent==null&&!branch.members.Contains(npc)&&npc.party==null,"native store removes party, branch, map and retains the same reserve NPC");
Check(npc.Timer==14400&&EClass.pc==hostActor,"native livestock timer and actor restoration retained");
Command(ReserveOperation.Store);Check(EClass.Home.listReserve.Count==1,"duplicate stores cannot duplicate reserves");
var storeResult=(ReserveStateDelta)host.Delta.Sent.Single();storeResult.Refresh();
Check(storeResult.ZoneUid==0&&storeResult.LivestockTimer==14400,"store result captures absence from map and livestock timer");
// Landing must also remove party membership if its separate result has not arrived.
EClass.Home.listReserve.Clear();branch.members.Add(npc);EClass._zone.AddCard(npc,8,9);party.members.Add(npc);npc.party=party;npc.Timer=0;
var residentUI=new BaseListPeople();residentUI.layer.multi.owners.Add(residentUI);
NetSession.Instance.Connection=client;ReserveManagementPatch.OpenResidentMenu(residentUI);storeResult.Apply(client);
Check(npc.party==null&&npc.parent==null&&npc.currentZone==null&&!branch.members.Contains(npc)&&EClass.Home.listReserve.Single().chara==npc,"client store result removes all live references without cloning");
Check(npc.Timer==14400&&residentUI.list.Refreshes==1&&residentUI.TabRefreshes==1,"timer and open resident list update on result");
storeResult.Apply(client);Check(EClass.Home.listReserve.Count==1,"repeated store results remain idempotent");
NetSession.Instance.Connection=host;Command(ReserveOperation.Recruit);
Check(branch.members.Contains(npc)&&npc.parent==EClass._zone&&EClass.Home.listReserve.Count==0,"stored NPC can be recruited back out");
Console.WriteLine($"{count} total hearthstone checks passed");

// Resident management shares the existing reserve UI refresh, but sends only the changed role.
var roleCallbacks=Types(people).SelectMany(t=>t.Methods).Where(m=>m.HasBody&&m.Body.Instructions.Any(i=>i.Operand is MethodReference r&&r.DeclaringType.Name=="FactionBranch"&&r.Name=="ChangeMemberType")).ToArray();
var maidCallbacks=Types(people).SelectMany(t=>t.Methods).Where(m=>m.HasBody&&m.Body.Instructions.Any(i=>i.OpCode==Mono.Cecil.Cil.OpCodes.Stfld&&i.Operand is FieldReference r&&r.Name=="uidMaid")).ToArray();
Check(roleCallbacks.Length==1&&maidCallbacks.Length==1,"installed resident role and maid callbacks each have one unambiguous match");
int ResidentPaths(TypeDefinition t, HashSet<string> seen){if(!seen.Add(t.FullName))return 0;return t.Fields.Where(f=>!f.IsStatic).Sum(f=>f.FieldType.Name=="Chara"?1:f.FieldType.DeclaringType?.Name=="BaseListPeople"?ResidentPaths(f.FieldType.Resolve(),new(seen)):0);}
Check(roleCallbacks.Concat(maidCallbacks).All(m=>ResidentPaths(m.DeclaringType,[])==1),"both native closures have one resident reference, following the cooldown's outer closure");
Check(roleCallbacks[0].Body.Instructions.Any(i=>i.Operand is MethodReference r&&r.Name=="SetInt"),"role callback owns cooldown write and must be intercepted as a whole");
var nativeBranch=module.Types.Single(t=>t.Name=="FactionBranch");
var nativeChange=nativeBranch.Methods.Single(m=>m.Name=="ChangeMemberType");
Check(new[]{"ClearBed","RefreshEfficiency","RefreshWorkElements","Validate"}.All(name=>nativeChange.Body.Instructions.Any(i=>i.Operand is MethodReference r&&r.Name==name)),"native member-type consequences verified against installed Elin");
Check(module.Types.Single(t=>t.Name=="PolicyManager").Methods.Single(m=>m.Name=="Validate").Body.Instructions.All(i=>i.OpCode==Mono.Cecil.Cil.OpCodes.Ret||i.OpCode==Mono.Cecil.Cil.OpCodes.Nop),"current policy validation has no additional state mutations");
var questBoard=module.Types.Single(t=>t.Name=="LayerQuestBoard");
var rerolls=Types(questBoard).SelectMany(t=>t.Methods).Where(m=>m.HasBody&&m.Body.Instructions.Any(i=>i.Operand is MethodReference r&&r.Name=="UpdateQuests")&&m.Body.Instructions.Any(i=>Equals(i.Operand,"notEnoughInfluence"))).ToArray();
Check(rerolls.Length==1&&rerolls[0].Body.Instructions.Any(i=>i.Operand is MethodReference r&&r.Name=="set_influence"),"installed reroll callback uniquely contains both generation and influence spending");
NetSession.Instance.Connection=client;
Check(!ClientQuestRerollPatch.Reroll()&&Msg.Last.Contains("host"),"client reroll blocked before native cost with explanation");
NetSession.Instance.Connection=host;Check(ClientQuestRerollPatch.Reroll(),"host reroll remains vanilla");
NetSession.Instance.Connection=null;Check(ClientQuestRerollPatch.Reroll(),"solo reroll remains vanilla");
NetSession.Instance.Connection=host;
npc.homeZone=EClass._zone;npc.faction=EClass.Home;npc.party=null;npc.memberType=FactionMemberType.Livestock;npc.Timer=0;npc.c_wasInPcParty=true;
void Role(FactionMemberType type,int zone=7)=>new ResidentCommandDelta{ZoneUid=zone,MemberUid=npc.uid,Operation=ResidentOperation.MemberType,MemberType=type}.Apply(host);
void Maid(bool desired)=>new ResidentCommandDelta{ZoneUid=7,MemberUid=npc.uid,Operation=ResidentOperation.Maid,Maid=desired}.Apply(host);
host.Delta.Sent.Clear();Role(FactionMemberType.Default);
Check(branch.TypeChanges==1&&npc.memberType==FactionMemberType.Default&&npc.Timer==34400&&!npc.c_wasInPcParty&&npc.BedsCleared==1,"host executes native role change and original cooldown");
Check(EClass.pc==hostActor&&host.Delta.Sent.Count==1,"actor restored and one authoritative result emitted");
var roleResult=(ResidentStateDelta)host.Delta.Sent.Single();
Check(roleResult.ClearBed&&roleResult.LivestockTimer==34400,"result carries cooldown and native bed invalidation");
Role(FactionMemberType.Default);Check(branch.TypeChanges==1&&npc.Timer==34400,"duplicate desired role cannot restart cooldown or repeat native changes");
Role(FactionMemberType.Livestock);Check(branch.TypeChanges==1,"host enforces resident-to-livestock cooldown");
EClass.world.date.Now=35000;Role(FactionMemberType.Livestock);Check(branch.TypeChanges==2&&npc.memberType==FactionMemberType.Livestock,"conversion allowed after native cooldown expires");
npc.party=party;Role(FactionMemberType.Default);Check(branch.TypeChanges==2,"party members cannot change resident role");npc.party=null;
npc.Remote=true;Maid(true);Role(FactionMemberType.Default);Check(branch.uidMaid==0&&branch.TypeChanges==2,"human characters protected from both management actions");npc.Remote=false;
Role(FactionMemberType.Default,8);Check(branch.TypeChanges==2,"stale-zone role request rejected");
host.Accept=false;Maid(true);Check(branch.uidMaid==0,"non-controlling peer cannot assign maid");host.Accept=true;
Maid(true);Maid(true);Check(branch.uidMaid==npc.uid,"maid request is an idempotent assignment");
branch.uidMaid=99;Maid(false);Check(branch.uidMaid==99,"stale unassign cannot remove another resident's newer maid assignment");
Maid(true);Maid(false);Check(branch.uidMaid==0,"assigned maid can be unassigned");
NetSession.Instance.Connection=client;npc.memberType=FactionMemberType.Livestock;npc.Timer=0;npc.c_wasInPcParty=true;
var oldChanges=branch.TypeChanges;roleResult.Apply(client);
Check(npc.memberType==FactionMemberType.Default&&npc.Timer==34400&&!npc.c_wasInPcParty&&branch.TypeChanges==oldChanges,"client applies role state without replaying native conversion");
var oldRefresh=residentUI.list.Refreshes;roleResult.Apply(client);Check(residentUI.list.Refreshes==oldRefresh+1,"duplicate result refreshes resident tabs without repeating conversion");
int oldRequests=client.Delta.Sent.Count;ResidentManagement.Submit(npc,ResidentOperation.Maid);
Check(client.Delta.Sent.Count==oldRequests+1&&branch.uidMaid==0,"client maid submission does not speculate locally");
var wrongZone=new ResidentStateDelta{ZoneUid=8,MemberUid=npc.uid,MaidUid=npc.uid};wrongZone.Apply(client);Check(branch.uidMaid==0,"old-map result cannot affect current settlement");
NetSession.Instance.Connection=host;ResidentManagement.Submit(npc,ResidentOperation.Maid);Check(branch.uidMaid==npc.uid,"host UI follows same validated management path");
var hostResidents=new BaseListPeople();ReserveManagementPatch.OpenResidentMenu(hostResidents);
ResidentManagement.Submit(npc,ResidentOperation.Maid);Check(hostResidents.list.Refreshes==1,"host resident UI refreshes after the routed operation too");
Console.WriteLine($"{count} total reserve/resident board checks passed");
var captured=new BaseListPeople.ResidentClosure{c=npc};var nested=new BaseListPeople.CooldownClosure{Outer=captured};
var path=ResidentManagementPatch.ResidentPath(nested.GetType());
object found=nested;foreach(var field in path)found=field.GetValue(found)!;
Check(path.Length==2&&ReferenceEquals(found,npc),"production resolver follows the cooldown's outer resident reference");
Check(ResidentManagementPatch.ResidentPath(captured.GetType()).Single().GetValue(captured)==npc,"production resolver handles the direct maid reference");
NetSession.Instance.Connection=client;
var priorTimer=npc.Timer;var priorRole=npc.memberType;
ResidentManagement.Submit((Chara)found,ResidentOperation.MemberType);
Check(npc.Timer==priorTimer&&npc.memberType==priorRole&&client.Delta.Sent.Last() is ResidentCommandDelta{Operation:ResidentOperation.MemberType,MemberUid:3},"client role submission requests the captured resident without speculative timer or role edits");
NetSession.Instance.Connection=null;
Check(ResidentManagementPatch.Click(nested,typeof(BaseListPeople.CooldownClosure).GetMethod("Role")!),"solo resident callback untouched");
Console.WriteLine($"{count} total reserve/resident board checks passed");

var dramaType=module.Types.Single(t=>t.Name=="DramaCustomSequence");
Check(dramaType.Methods.Where(m=>m.HasBody).Any(m=>m.Body.Instructions.Any(i=>Equals(i.Operand,"_daMakeMaid"))),"installed ally dialogue exposes the maid assignment step");
Check(Types(dramaType).SelectMany(t=>t.Methods).Where(m=>m.HasBody).Any(m=>m.Body.Instructions.Any(i=>i.OpCode==Mono.Cecil.Cil.OpCodes.Stfld&&i.Operand is FieldReference r&&r.Name=="uidMaid")),"installed ally dialogue bypasses resident-board callback with direct maid write");
DramaCustomSequence MaidDialogue(out DramaEventMethod action){action=new(){action=()=>throw new Exception("Unrouted native maid write")};return new(){events=[new(){step="_daMakeMaid"},action]};}
NetSession.Instance.Connection=client;branch.uidMaid=npc.uid;
var clientTalk=MaidDialogue(out var clientMaid);ResidentMaidDialoguePatch.After(clientTalk,npc);clientMaid.action();
Check(client.Delta.Sent.Last() is ResidentCommandDelta{Operation:ResidentOperation.Maid,Maid:true,MemberUid:3},"ally dialogue sends explicit assign even if client already sees this maid");
Check(branch.uidMaid==npc.uid&&clientTalk.Jump==clientTalk.StepEnd,"client dialogue avoids speculative assignment and premature success reply");
NetSession.Instance.Connection=host;branch.uidMaid=0;npc.party=party;
var hostTalk=MaidDialogue(out var hostMaid);ResidentMaidDialoguePatch.After(hostTalk,npc);hostMaid.action();
Check(branch.uidMaid==npc.uid&&hostTalk.Jump=="","host ally dialogue uses shared validation and retains vanilla success reply");
hostMaid.action();Check(branch.uidMaid==npc.uid,"repeated dialogue never toggles maid off");
npc.Remote=true;branch.uidMaid=0;hostMaid.action();
Check(branch.uidMaid==0&&hostTalk.Jump==hostTalk.StepEnd,"dialogue cannot assign a human player and does not claim success");npc.Remote=false;npc.party=null;
NetSession.Instance.Connection=null;var soloTalk=MaidDialogue(out var soloMaid);var nativeCalls=0;soloMaid.action=()=>nativeCalls++;
ResidentMaidDialoguePatch.After(soloTalk,npc);soloMaid.action();Check(nativeCalls==1,"solo maid dialogue retains its original native action");
Console.WriteLine($"{count} total reserve/resident/dialogue checks passed");
