using ElinTogether.Models;
using ElinTogether.Net;
using Mono.Cecil;
using Mono.Cecil.Cil;

int checks = 0;
void Check(bool ok, string why) { if (!ok) throw new Exception(why); Console.WriteLine("PASS " + why); checks++; }
var managed = Path.GetDirectoryName(args.Single())!;
using var native = ModuleDefinition.ReadModule(args.Single());
var callbacks = native.Types.Single(t => t.Name == "BaseListPeople").NestedTypes.SelectMany(t => t.Methods).Where(m => m.HasBody).ToArray();
Check(callbacks.Count(m => m.Body.Instructions.Any(i => i.Operand is MethodReference { Name: "set_c_altName" })) == 1, "native resident rename has one confirmation callback");
Check(callbacks.Count(m => m.Body.Instructions.Any(i => i.OpCode == OpCodes.Stfld && i.Operand is FieldReference { Name: "pccData" })) == 2, "native PCC toggles have two mutation callbacks");
using var ui = ModuleDefinition.ReadModule(Path.Combine(managed, "Plugins.UI.dll"));
var kill = ui.Types.Single(t => t.Name == "Layer").Methods.Single(m => m.Name == "Kill").Body.Instructions;
Check(kill.ToList().FindIndex(i => i.Operand is MethodReference { Name: "OnKill" }) < kill.ToList().FindIndex(i => i.Operand is FieldReference { Name: "onKill" }), "native editor applies OnKill before our onKill listener");
using var actorSystem = ModuleDefinition.ReadModule(Path.Combine(managed, "Plugins.ActorSystem.dll"));
var pcc = actorSystem.Types.Single(t => t.Name == "PCCData");
Check(pcc.Fields.Where(f => f.CustomAttributes.Any(a => a.AttributeType.Name == "JsonPropertyAttribute")).Select(f => f.Name).SequenceEqual(new[] { "map" }), "only PCC map is native saved appearance state");

var host = new ElinNetHost(); var client = new ElinNetClient(); host.ActiveRemoteCharas[1] = new() { uid = 719 };
NetSession.Instance.Connection = host;
var c = new Chara { c_altName = "old" }; EClass._map.Members.Add(c); EClass.scene.syncList.Add(c.renderer);
ResidentCosmeticRequest Change(Action<ResidentCosmetics> change) { var after = ResidentCosmetics.Capture(c); change(after); return new() { ZoneUid = 10, MemberUid = c.uid, Before = ResidentCosmetics.Capture(c), After = after }; }
var rename = Change(s => s.Name = "new"); rename.Apply(host); rename.Apply(host);
Check(c.c_altName == "new" && c.Builds == 0, "rename is idempotent and doesn't rebuild renderer");
var stale = rename; c.c_altName = "host newer"; stale.Apply(host);
Check(c.c_altName == "host newer" && host.Replies.Count == 1, "stale rename cannot overwrite host edit");
var independent = Change(s => s.Portrait = "portrait1"); c.c_altName = "another name"; independent.Apply(host);
Check(c.c_altName == "another name" && c.c_idPortrait == "portrait1", "different cosmetic fields don't overwrite one another");
var beforeRenderer = c.renderer;
var parts = Change(s => s.Parts = new() { ["body"] = ["female", "body1", "ffffff"], ["hair"] = ["female", "hair1", "112233"] });
parts.Apply(host);
Check(c.pccData!.map["hair"][2] == "112233" && c.Builds == 1, "PCC parts and colors applied together");
Check(beforeRenderer.Leaves == 1 && !EClass.scene.syncList.Contains(beforeRenderer) && EClass.scene.syncList.Contains(c.renderer) && c.renderer.Enters == 1, "renderer handed off without duplicate screen entries");
parts.After.Parts!["body"][1] = "mutated packet";
Check(c.pccData.map["body"][1] == "body1", "saved PCC arrays don't alias network data");
var captured = ResidentCosmetics.Capture(c); c.pccData.map["body"][1] = "body2";
Check(captured.Parts!["body"][1] == "body1", "editor baseline doesn't alias live PCC previews");
var malformed = Change(s => s.Parts = new() { ["body"] = ["bad"] }); malformed.Apply(host);
Check(c.pccData.map["body"][1] == "body2", "malformed PCC entry rejected before mutation");
var disable = Change(s => s.Parts = null); disable.Apply(host);
Check(c.pccData == null, "PCC can be switched off");
c.sourceCard.idActor = "unique"; Change(s => s.Skin = "skin1").Apply(host);
Check(c.c_idSpriteReplacer == null, "fixed actor appearance cannot be edited");
Change(s => s.Name = "unique name").Apply(host);
Check(c.c_altName == "unique name", "fixed appearance still permits native rename"); c.sourceCard.idActor = "";
c.Protected = true; Change(s => s.Name = "bad human edit").Apply(host);
Check(c.c_altName == "unique name", "player and dormant character profiles protected"); c.Protected = false;
c.Home = false; Change(s => s.Name = "outsider").Apply(host);
Check(c.c_altName == "unique name", "non-resident edit rejected"); c.Home = true;
host.AcceptInput = false; Change(s => s.Name = "inactive").Apply(host); host.AcceptInput = true;
Check(c.c_altName == "unique name", "inactive client cannot edit");
var wrong = Change(s => s.Name = "wrong zone");
EClass._zone.uid = 11; wrong.Apply(host); EClass._zone.uid = 10;
Check(c.c_altName == "unique name", "wrong-zone request rejected");
NetSession.Instance.Connection = client;
var edit = ResidentAppearance.Begin(c); c.c_altName = "preview"; ResidentAppearance.Finish(edit);
Check(client.Delta.Items.Single() is ResidentCosmeticRequest && c.c_altName == "preview", "confirmed client edit emits one request after local preview");
var state = (ResidentCosmeticState)host.Delta.Items.Last(); state.Apply(client);
Check(c.c_altName == "unique name" && EClass._map.FindChara(c.uid) == c, "authoritative response repairs preview without replacing character");
var builds = c.Builds; state.Apply(client);
Check(c.Builds == builds && client.Delta.Items.Count == 1, "replayed state does not rebuild or echo another request");
var abandoned = ResidentAppearance.Begin(c); c.c_altName = "abandoned"; NetSession.Instance.Connection = null; ResidentAppearance.Finish(abandoned);
Check(client.Delta.Items.Count == 1 && ResidentAppearance.Begin(c) == null, "closed session and solo do not emit edits");
NetSession.Instance.Connection = host;
var local = ResidentAppearance.Begin(c); c.c_altName = "host confirmed"; var count = host.Delta.Items.Count; ResidentAppearance.Finish(local);
Check(host.Delta.Items.Count == count + 1, "host native edit publishes through same result channel");
Console.WriteLine($"{checks} resident checks passed; installed native boundaries verified, game/transport simulated.");
