using ElinTogether.Models;
using ElinTogether.Net;
int checks=0;
void Check(bool ok,string message){if(!ok)throw new Exception(message);checks++;Console.WriteLine("PASS "+message);}
var host=new ElinNetHost();NetSession.Instance.Connection=host;
var own=new Chara{uid=1};var a=new Chara{uid=719};var b=new Chara{uid=720};
EClass.player.chara=own;host.ActiveRemoteCharas[1]=a;host.ActiveRemoteCharas[2]=b;
var god=new Religion{id="earth",giftRank=2,mood=10};var second=new Religion{id="luck",giftRank=1,mood=20};
EClass.game.religions.list=[god,second];own.faith=god;a.faith=god;b.faith=second;EClass._map.charas=[own,a,b];
var altar=new TraitAltar{Deity=second};var tile=new Thing{uid=2,trait=altar};EClass._map.things.Add(tile);
PersonalFaith.BeginSession(a);PersonalFaith.BeginSession(b);
Check(PersonalFaith.Read(a).Gods.Count==0,"migration does not copy the host's gift claims onto a remote human");
FaithRequestDelta Request(FaithAction action)=>new(){Id=Guid.NewGuid(),Action=action,ZoneUid=1};
FaithResultDelta Last()=> (FaithResultDelta)host.Replies.Last().Delta;
var pray=Request(FaithAction.Pray);FaithTransactions.Resolve(host,1,pray);
Check(a.hp==100&&a.mana.value==100&&PersonalFaith.Read(a).Gods["earth"].Gifts==1,"prayer runs with remote personal god history and returns healing");
Check(god.giftRank==2&&god.mood==10&&EClass.pc==own&&!EClass.player.prayed&&FaithTransactions.Actor==null,"host character and religion globals restored after remote prayer");
Check(Last().Vitals.Length==1&&Last().Vitals[0].Owner.Uid==a.uid,"reply contains resolved HP and mana for affected character");
var calls=ActPray.Calls;FaithTransactions.Resolve(host,1,pray);
Check(ActPray.Calls==calls,"duplicate request cannot grant a second gift or heal");
FaithTransactions.Resolve(host,1,Request(FaithAction.Pray));
Check(PersonalFaith.Read(a).Gods["earth"].Gifts==1,"same-day prayer consults personal eligibility");
FaithTransactions.Resolve(host,2,Request(FaithAction.Pray));
Check(PersonalFaith.Read(b).Gods["luck"].Gifts==1,"other player has independent prayer/gift history");
var persisted=a.GetStr(PersonalFaith.SaveKey);FaithTransactions.Reset();a.SetStr(PersonalFaith.SaveKey,persisted);PersonalFaith.BeginSession(a);
FaithTransactions.Resolve(host,1,Request(FaithAction.Pray));
Check(PersonalFaith.Read(a).Gods["earth"].Gifts==1,"reload/session reset does not reset saved prayer day");
EClass.world.date.Day++;PersonalFaith.AdvanceActive(a);
Check(a.c_daysWithGod==1,"active remote worship days advance on host");
FaithTransactions.Resolve(host,1,Request(FaithAction.Pray));
Check(PersonalFaith.Read(a).Gods["earth"].Gifts==2,"next-day prayer uses existing personal history");
var days=b.c_daysWithGod;EClass.world.date.Day+=5;PersonalFaith.BeginSession(b);
Check(b.c_daysWithGod==days,"rejoining dormant character does not earn offline worship days");
var convert=Request(FaithAction.Convert);convert.God="luck";a.Distance=9;FaithTransactions.Resolve(host,1,convert);
Check(a.faith==god,"conversion rejected without a nearby matching altar");
a.Distance=1;convert=Request(FaithAction.Convert);convert.God="luck";FaithTransactions.Resolve(host,1,convert);
Check(a.faith==second&&own.faith==god&&god.mood==10,"conversion changes chosen player without leaking religion globals");
var food=new Thing{uid=4,Num=5,parent=a};var offer=Request(FaithAction.Offer);offer.Item=food;offer.Altar=tile;offer.Quantity=2;
FaithTransactions.Resolve(host,2,offer);Check(food.Num==5&&altar.Offers==0,"cannot sacrifice another player's item");
offer=Request(FaithAction.Offer);offer.Item=food;offer.Altar=tile;offer.Quantity=2;FaithTransactions.Resolve(host,1,offer);
Check(food.Num==3&&altar.Offered==2,"partial offering consumes only the selected quantity");
FaithTransactions.Resolve(host,1,offer);Check(food.Num==3&&altar.Offered==2,"duplicate offering cannot consume another portion");
altar.Run=(actor,t)=>{t.SetBlessedState(BlessedState.Blessed);altar.SetDeity("earth");};
offer=Request(FaithAction.Offer);offer.Item=food;offer.Altar=tile;offer.Quantity=1;FaithTransactions.Resolve(host,1,offer);
Check(Last().Remainder?.Find().parent==a&&Last().RemainderBlessing==1&&Last().AltarGod=="earth","water/remainders and altar change use resolved results");
OwnerProgressionAwards.Pending[a]=[1];calls=ActPray.Calls;FaithTransactions.Resolve(host,1,Request(FaithAction.Pray));
Check(ActPray.Calls==calls,"gift eligibility waits for pending owner progression acknowledgements");OwnerProgressionAwards.Pending.Clear();
ActPray.Throw=true;FaithTransactions.Resolve(host,1,Request(FaithAction.Pray));ActPray.Throw=false;
Check(EClass.pc==own&&god.giftRank==2&&second.giftRank==1&&FaithTransactions.Actor==null,"exception restores all host context and returns resolved state");
var client=new ElinNetClient();NetSession.Instance.Connection=client;EClass.player.chara=a;FaithTransactions.Reset();
FaithTransactions.Submit(FaithAction.Pray);FaithTransactions.Submit(FaithAction.Pray);
Check(client.Delta.Items.Count==1,"client queues one pending worship action instead of predicting twice");
var id=((FaithRequestDelta)client.Delta.Items[0]).Id;FaithTransactions.Complete(id);FaithTransactions.Submit(FaithAction.Pray);
Check(client.Delta.Items.Count==2,"reply releases pending action gate");
Check(FaithTransactions.ReceiveOnce(id)&&!FaithTransactions.ReceiveOnce(id),"duplicate result cannot overwrite newer client state twice");
a.elements.SetBase(306,10);a.elements.SetBase(85,9);a.elements.ExpCalls.Clear();
FaithOfferingProgression.Apply(a,30,false);
Check(a.Evalue(85)==10&&a.elements.ExpCalls.Contains((85,20))&&a.elements.ExpCalls.Contains((306,6)),"offering piety cap and faith training follow vanilla owner calculation order");
a.elements.SetBase(306,10);a.elements.SetBase(85,1);a.elements.ExpCalls.Clear();
FaithOfferingProgression.Apply(a,3,true);
Check(a.Evalue(85)==3&&!a.elements.ExpCalls.Any(c=>c.Id==306)&&EClass.player.Karma==-1,"low piety does not train faith early and contraband penalty is applied once by owner");
// Transport ordering: the host can queue its daily state, then send a newer
// transaction result immediately before that older queued packet is flushed.
var oldState=a.GetStr(PersonalFaith.SaveKey)!;
var newer=PersonalFaith.Read(a);newer.PrayerDay=EClass.world.date.Day;newer.Days=20;PersonalFaith.Save(a,newer);
var newest=a.GetStr(PersonalFaith.SaveKey)!;
new FaithResultDelta{Owner=a,PersonalState=oldState,FaithId="earth"}.Apply(client);
Check(a.GetStr(PersonalFaith.SaveKey)==newest&&a.faith==second,"older daily state cannot undo a newer conversion or prayer result");
a.c_daysWithGod=21;PersonalFaith.RestoreDay();
Check(a.c_daysWithGod==20&&EClass.player.prayed,"daily callback does not double-count a received day or clear today's prayer");
EClass.world.date.Day++;PersonalFaith.RestoreDay();
Check(a.c_daysWithGod==21&&!EClass.player.prayed,"client day advance before host state expires cooldown without losing worship days");
NetSession.Instance.Connection=host;EClass.player.chara=own;FaithTransactions.Reset();
var oldMood=second.mood;PersonalFaith.AdvanceHour(a);
Check(second.mood==oldMood&&PersonalFaith.Read(a).Gods["luck"].Mood==1,"remote hourly mood advances independently and restores host's religion instance");
var previousCount=host.Delta.Items.Count;
using(FaithTransactions.BeginLocal(own,altar,food)) {
 Check(FaithTransactions.Actor==own,"native host worship enters the same outcome boundary");
 b.mana.value+=3;altar.SetDeity("luck");
}
var native=(FaithResultDelta)host.Delta.Items.Last();
Check(FaithTransactions.Actor==null&&host.Delta.Items.Count==previousCount+1&&native.Vitals.Single().Owner.Uid==b.uid&&native.AltarGod=="luck","native host worship broadcasts changed ally mana and altar state once");
calls=ActPray.Calls;var passive=Request(FaithAction.Pray);passive.Passive=true;FaithTransactions.Resolve(host,1,passive);
Check(ActPray.Calls==calls,"passive prayer requires the actual believer feat");
a.isDead=true;FaithTransactions.Resolve(host,1,Request(FaithAction.Pray));a.isDead=false;
Check(ActPray.Calls==calls,"dead character cannot invoke worship");
var wrongZone=Request(FaithAction.Pray);wrongZone.ZoneUid=999;FaithTransactions.Resolve(host,1,wrongZone);
Check(ActPray.Calls==calls,"stale-zone request does not execute worship");
var countBefore=food.Num;var offersBefore=altar.Offers;
foreach(var quantity in new[]{0,food.Num+1}) {
 var invalid=Request(FaithAction.Offer);invalid.Item=food;invalid.Altar=tile;invalid.Quantity=quantity;FaithTransactions.Resolve(host,1,invalid);
}
Check(food.Num==countBefore&&altar.Offers==offersBefore,"invalid offering quantity cannot consume or split inventory");
var retries=host.Replies.Count;FaithTransactions.Resolve(host,1,wrongZone);
Check(host.Replies.Count==retries+1&&Last().Id==wrongZone.Id,"duplicate request resends its cached acknowledgement without re-executing");
var campaign=Request(FaithAction.Convert);campaign.God=god.id;campaign.Conversion=Religion.ConvertType.Campaign;
a.Distance=99;PersonalFaith.AdvanceActive(a);days=PersonalFaith.Read(a).Days;FaithTransactions.Resolve(host,1,campaign);
Check(a.faith==god&&a.c_daysWithGod==days,"vanilla healing campaign conversion preserves conversion type and requires no altar");
Console.WriteLine($"{checks} checks passed");
