using ElinTogether.Models;
using ElinTogether.Net;

int checks = 0;
void Check(bool ok, string label) { if (!ok) throw new Exception(label); checks++; Console.WriteLine("PASS " + label); }
var hostTrap = new Thing { uid = 1 };
var clientTrap = new Thing { uid = 2, isHidden = false };
var unknown = new Thing { uid = 3 };
var destroyed = new Thing { uid = 4, isDestroyed = true };
var offMap = new Thing { uid = 5, pos = new Point { IsValid = false } };
var medal = new Thing { uid = 6, trait = new object() };
EClass._map.things = [hostTrap, clientTrap, unknown, destroyed, offMap, medal];
var client = new ElinNetClient(); NetSession.Instance.Connection = client;
Check(TrapDiscoverySync.Capture().SequenceEqual([2]), "capture only discovered live map traps");
TrapDiscoverySync.Apply(8, [1]);
Check(hostTrap.isHidden && client.Delta.Sent.Count == 0, "wrong-zone snapshot ignored");
TrapDiscoverySync.Apply(7, null);
Check(hostTrap.isHidden && client.Delta.Sent.Count == 0, "absent snapshot ignored");
TrapDiscoverySync.Apply(7, [1, 4, 5, 6, 999]);
Check(!hostTrap.isHidden && hostTrap.Refreshes == 1, "host discovery refreshes client trap");
Check(unknown.isHidden && destroyed.isHidden && offMap.isHidden && medal.isHidden, "unknown traps, destroyed/off-map cards and medals untouched");
var report = (TrapDiscoveryDelta)client.Delta.Sent.Single();
Check(report.ZoneUid == 7 && report.Revealed.SequenceEqual([2]), "client reports only its missing discovery");
TrapDiscoverySync.Apply(7, [1]);
Check(hostTrap.Refreshes == 1 && client.Delta.Sent.Count == 2, "repeat snapshot retries report without repeated refresh");
TrapDiscoverySync.Apply(7, [1, 2]);
Check(client.Delta.Sent.Count == 2, "host acknowledgement stops retry");
var host = new ElinNetHost(); NetSession.Instance.Connection = host;
clientTrap.isHidden = true;
report.OriginPeer = 9; report.Apply(host);
Check(clientTrap.isHidden, "unknown peer rejected");
host.ActiveRemoteCharas[9] = new Chara { IsInActiveMap = false }; report.Apply(host);
Check(clientTrap.isHidden, "off-map peer rejected");
host.ActiveRemoteCharas[9].IsInActiveMap = true;
EClass._zone.uid = 8; report.Apply(host);
Check(clientTrap.isHidden, "stale-zone report rejected");
EClass._zone.uid = 7; report.Apply(host);
Check(!clientTrap.isHidden && TrapDiscoverySync.Capture().ToHashSet().SetEquals([1, 2]), "valid client discovery reaches host snapshot");
report.Apply(host);
Check(clientTrap.Refreshes == 1, "duplicate report idempotent");
hostTrap.isHidden = true; report.Apply(client); TrapDiscoverySync.Apply(7, [1]);
Check(hostTrap.isHidden, "client cannot consume reports and host ignores reconciliation");
NetSession.Instance.Connection = null; TrapDiscoverySync.Apply(7, [1]);
Check(hostTrap.isHidden, "solo unchanged");
Console.WriteLine($"{checks} checks passed");
