<Project Sdk="Microsoft.NET.Sdk">
<PropertyGroup><OutputType>Exe</OutputType><TargetFramework>net11.0</TargetFramework><ImplicitUsings>enable</ImplicitUsings><Nullable>enable</Nullable><LangVersion>preview</LangVersion></PropertyGroup>
<ItemGroup>
<Compile Include="../../ElinTogether/Net/Client/ElinNetClientStartup.cs" Link="ElinNetClientStartup.cs" />
<Compile Include="../../ElinTogether/Patches/DeltaEvents/Inventory/InvSortEvent.cs" Link="InvSortEvent.cs" />
</ItemGroup>
</Project>
