using ElinTogether.Models;
using ElinTogether.Net;
using Newtonsoft.Json.Linq;
int checks=0;
void Check(bool ok,string text){if(!ok)throw new Exception(text);checks++;Console.WriteLine("PASS "+text);}
void Reject(Action action,string text){try{action();}catch(Exception){Check(true,text);return;}throw new Exception("Expected rejection: "+text);}
var zone=new Zone{uid=7};var original=new Chara{uid=1,NameSimple="host",homeZone=zone,currentZone=zone};
var guest=new Chara{uid=719,NameSimple="client",homeZone=zone,currentZone=zone,c_daysWithGod=12};
guest.SetBool("remote_chara",true);guest.SetInt(PersonalKarma.ValueKey,-12);
var tool=new Thing{uid=900,id="axe",Num=1};guest.things.Add(tool);guest.equipment=tool;
var npc=new Chara{uid=20,NameSimple="cat",homeZone=zone,currentZone=zone};
EClass.game.cards.globalCharas[1]=original;EClass.game.cards.globalCharas[719]=guest;EClass.game.cards.globalCharas[20]=npc;
var party=new Party();party.AddMemeber(original);party.AddMemeber(npc);party.SetLeader(original);
EClass.player.chara=original;EClass.player.uidChara=1;EClass.player.zone=zone;
EClass.player.totalFeat=40;EClass.player.stats.kills=123;EClass.player.hotbars.Slot=5;EClass.player.karma=18;
EClass.game.religions.list=[new Religion{id="earth",giftRank=2,mood=7}];
Check(SoloCharacterSelection.Candidates().Select(c=>c.uid).SequenceEqual(new[]{1,719}),"selector offers saved humans, not ordinary companions");
NetSession.Instance.Connection=new ElinNetClient();Reject(()=>SoloCharacterSelection.Select(guest),"live client cannot switch");
NetSession.Instance.Connection=new ElinNetHost();Reject(()=>SoloCharacterSelection.Select(guest),"running server cannot switch");NetSession.Instance.Connection=null;
guest.isDead=true;Reject(()=>SoloCharacterSelection.Select(guest),"dead character cannot be activated");guest.isDead=false;
guest.host=npc;Reject(()=>SoloCharacterSelection.Select(guest),"mounted character cannot be activated");guest.host=null;
OwnerProgressionAwards.Pending=1;Reject(()=>SoloCharacterSelection.Select(guest),"unacknowledged multiplayer rewards block switching");OwnerProgressionAwards.Pending=0;
var before=Game.SaveCalls;guest.SetStr(SoloPlayerProfile.SaveKey,"{\"Version\":99}");
Reject(()=>SoloCharacterSelection.Select(guest),"unknown profile version fails before save or mutation");Check(Game.SaveCalls==before&&EClass.pc==original,"failed preflight preserves active player");guest.SetStr(SoloPlayerProfile.SaveKey,null);
Game.FailSave=true;Reject(()=>SoloCharacterSelection.Select(guest),"failed save aborts switch");Game.FailSave=false;
Check(EClass.pc==original&&Game.LoadCalls==0,"save failure does not reload or replace character");
GameIO.FailBackup=true;Reject(()=>SoloCharacterSelection.Select(guest),"failed full-world backup aborts switch");GameIO.FailBackup=false;
Check(EClass.pc==original&&Game.LoadCalls==0,"backup failure preserves current world and player");
Game.FailNextLoad=true;Reject(()=>SoloCharacterSelection.Select(guest),"load failure restores last saved original world");
Check(EClass.pc.uid==1&&!SoloCharacterSelection.IsSoloCharacter,"failed reload clears pending selection before recovery");
guest=EClass.game.cards.globalCharas.Find(719)!;
Game.SkipSelectionHook=true;
Reject(()=>SoloCharacterSelection.Select(guest),"missing offline hook reports failed switch instead of silent success");
Game.SkipSelectionHook=false;
Check(EClass.pc.uid==1&&!SoloCharacterSelection.IsSoloCharacter,"missing hook recovers original character and clears pending switch");
guest=EClass.game.cards.globalCharas.Find(719)!;
SoloCharacterSelection.Select(guest);
Check(EClass.pc.uid==719&&EClass.player.uidChara==719&&SoloCharacterSelection.IsSoloCharacter,"selection applies during normal save/reload and marks solo role");
Check(EClass.pc.party!.leader==EClass.pc&&EClass.pc.party.members.Select(c=>c.uid).Order().SequenceEqual(new[]{20,719}),"selected character leads existing companion party; original human is parked");
Check(EClass.pc.party.uidMembers.Order().SequenceEqual(new[]{20,719}),"pre-load switch updates serialized party membership without live branch callbacks");
original=EClass.game.cards.globalCharas.Find(1)!;
Check(original.GetBool("remote_chara")&&!EClass.pc.GetBool("remote_chara")&&EClass.pc.GetInt(CINT.IsPC)==1&&original.GetInt(CINT.IsPC)==0,"active/dormant flags agree so cleanup cannot target new player");
Check(EClass.pc.things.Count==1&&EClass.pc.things[0].uid==900&&ReferenceEquals(EClass.pc.equipment,EClass.pc.things[0]),"inventory UID and equipment reference survive without cloning items");
Check(EClass.player.karma==-12&&EClass.pc.c_daysWithGod==12,"saved personal karma and worship days follow selected character");
Check(EClass.player.totalFeat==0&&EClass.player.stats.kills==0&&EClass.player.hotbars.Initialized,"missing legacy profile starts unknown counters and hotbars fresh instead of copying host");
Check(EClass.player.bankMoney==900&&EClass.player.recipes.craftedRecipes.Contains("axe")&&EClass.player.knownBGMs.SetEquals(new[]{1,8})&&EClass.player.WorldQuest=="guild phase 12","world finances, recipe claims, collections and quest state stay intact");
Check(original.GetStr(SoloPlayerProfile.SaveKey)!.Contains("123"),"original player's personal counters retained on parked character");
EClass.player.totalFeat=9;EClass.player.stats.kills=7;EClass.player.hotbars.Slot=3;EClass.player.karma=-8;
EClass.game.religions.list[0].giftRank=1;EClass.player.prayed=true;EClass.game.Save();Game.Load(Game.id,false);
Check(EClass.pc.uid==719&&EClass.player.totalFeat==9&&EClass.player.stats.kills==7&&EClass.game.religions.list[0].giftRank==1,"ordinary save/reload retains selected character and personal progress");
SoloCharacterSelection.Select(EClass.game.cards.globalCharas.Find(1)!);
Check(EClass.pc.uid==1&&!SoloCharacterSelection.IsSoloCharacter&&EClass.player.totalFeat==40&&EClass.player.stats.kills==123&&EClass.player.hotbars.Slot==5,"switching back restores original personal profile and original hosting role");
Check(EClass.player.karma==18&&EClass.game.religions.list[0].giftRank==2&&!EClass.player.prayed,"switching back restores original karma and god gift/prayer history");
SoloCharacterSelection.Select(EClass.game.cards.globalCharas.Find(719)!);
Check(EClass.player.totalFeat==9&&EClass.player.stats.kills==7&&EClass.player.hotbars.Slot==3&&EClass.player.karma==-8,"second switch restores client's new solo progress instead of resetting it");
var folder=SoloCharacterSelection.Export(EClass.pc);
var backup=JObject.Parse(File.ReadAllText(Path.Combine(folder,"character-719.json")));
Check((int)backup["uid"]! ==719&&backup["character"]!=null&&backup["personalProfile"]!=null&&backup["faith"]!=null,"JSON export contains character and saved personal/faith records");
Check(!Directory.GetFiles(folder,"*.tmp").Any()&&GameIO.Backups>=3,"exports finalize atomically and every completed switch makes a world backup");
Check(EClass.game.cards.globalCharas.Count==3,"repeated switches retain both original humans and companion without duplicate characters");
EClass.sources.elements.alias["pray"]=new(){id=10};EClass.pc.Elements.Add(10);
InvPlaceAbilityDelta.StoreLayout(EClass.pc,[new(){Alias="pray",InvX=2,InvY=0},new(){Alias="unknown",InvX=3,InvY=0}]);
var inventoryCount=EClass.pc.things.Count;InvPlaceAbilityDelta.RestoreLayout(EClass.pc);
Check(EClass.pc.things.Count==inventoryCount+1&&EClass.pc.things.Last().c_idAbility=="pray","saved ability layout restores valid tokens and ignores unknown skills");
InvPlaceAbilityDelta.RestoreLayout(EClass.pc);
Check(EClass.pc.things.Count==inventoryCount+1,"repeated layout restoration does not duplicate existing ability tokens");
Check(SoloPlayerProfile.HasMissingHistory(EClass.pc),"legacy history marker survives solo saves and switches");
var fresh=new Chara{uid=888};SoloPlayerProfile.Initialize(fresh,legacy:false);
Check(!SoloPlayerProfile.HasMissingHistory(fresh),"new character receives a complete fresh profile");
var remote=new Chara{uid=EClass.pc.uid};SoloPlayerProfile.Initialize(remote,legacy:true);
var session=Guid.NewGuid();var sender=new PlayerProfileChannel(EClass.pc.uid,session);var receiver=new PlayerProfileChannel(remote.uid,session);
var first=sender.Capture(EClass.pc,EClass.player)!;
Check(first.Revision==1&&first.Session==session,"first client checkpoint is session-bound");
var hostTotal=EClass.player.totalFeat;var hostKarma=EClass.player.karma;
var receipt=receiver.Accept(remote,first)!;
Check(receipt.Revision==1&&EClass.player.totalFeat==hostTotal&&EClass.player.karma==hostKarma,"host stores remote profile without mutating live host Player");
Check(receiver.Accept(remote,first)?.Revision==1,"identical retry is acknowledged again");
Check(sender.Capture(EClass.pc,EClass.player)?.Revision==1,"unacknowledged unchanged checkpoint is retried");
sender.Acknowledge(receipt);
Check(sender.Capture(EClass.pc,EClass.player)==null,"acknowledged unchanged profile is not resent");
EClass.player.hotbars.Slot=6;EClass.player.knownSongs["song"]=12;EClass.player.wellWished=true;
EClass.player.hotbars.Items.Add(new HotItemAbility{Alias="pray"});
var second=sender.Capture(EClass.pc,EClass.player)!;
Check(second.Revision==2,"changed personal data advances checkpoint revision");
sender.Acknowledge(receipt);Check(sender.Capture(EClass.pc,EClass.player)?.Revision==2,"old receipt cannot acknowledge newer data");
var receipt2=receiver.Accept(remote,second)!;var accepted=remote.GetStr(SoloPlayerProfile.SaveKey);
Check(ReferenceEquals(sender.Pending,second),"retry reuses cached profile without serializing live Player");
sender.Acknowledge(receipt2);Check(sender.Pending==null,"receipt retires cached pending checkpoint");
Check(receiver.Accept(remote,first)==null&&remote.GetStr(SoloPlayerProfile.SaveKey)==accepted,"out-of-order checkpoint cannot roll back saved progress");
PlayerProfileCheckpoint CopyPacket(int? uid=null,Guid? epoch=null,long? rev=null,string? json=null)=>new(){OwnerUid=uid??second.OwnerUid,Session=epoch??session,Revision=rev??second.Revision,Json=json??second.Json};
Check(receiver.Accept(remote,CopyPacket(uid:1))==null,"checkpoint cannot target another player's UID");
Check(receiver.Accept(remote,CopyPacket(epoch:Guid.NewGuid()))==null,"old connection token cannot update current profile");
Check(receiver.Accept(fresh,second)==null,"peer channel cannot be applied to another registered character");
Check(receiver.Accept(remote,CopyPacket(json:first.Json))==null,"same revision with different data is rejected");
var bad=JObject.Parse(second.Json);bad["Version"]=99;
Reject(()=>receiver.Accept(remote,CopyPacket(rev:3,json:bad.ToString())),"unsupported network profile version is rejected");
bad=JObject.Parse(second.Json);((JObject)bad["Fields"]!).Remove("hotbars");
Reject(()=>receiver.Accept(remote,CopyPacket(rev:3,json:bad.ToString())),"partial checkpoint is rejected atomically");
bad=JObject.Parse(second.Json);bad["Fields"]!["stats"]="null";
Reject(()=>receiver.Accept(remote,CopyPacket(rev:3,json:bad.ToString())),"required object cannot be replaced with null");
bad=JObject.Parse(second.Json);bad["Fields"]!["bankMoney"]="0";
Reject(()=>receiver.Accept(remote,CopyPacket(rev:3,json:bad.ToString())),"shared world fields are not accepted in a personal profile");
bad=JObject.Parse(second.Json);bad["Fields"]!["stats"]="{\"$type\":\"System.IO.FileInfo, System.Private.CoreLib\",\"OriginalPath\":\"unwanted\"}";
Reject(()=>receiver.Accept(remote,CopyPacket(rev:3,json:bad.ToString())),"network profile cannot instantiate arbitrary CLR types");
Reject(()=>receiver.Accept(remote,CopyPacket(rev:3,json:new string('x',SoloPlayerProfile.MaxJsonLength+1))),"oversized profile rejected");
Check(remote.GetStr(SoloPlayerProfile.SaveKey)==accepted,"invalid checkpoints leave last accepted record intact");
bad=JObject.Parse(second.Json);bad["LegacyHistoryMissing"]=false;
receiver.Accept(remote,CopyPacket(rev:3,json:bad.ToString()));
Check(SoloPlayerProfile.HasMissingHistory(remote),"client checkpoint cannot erase missing-history provenance");
var reloaded=Newtonsoft.Json.JsonConvert.DeserializeObject<Chara>(Newtonsoft.Json.JsonConvert.SerializeObject(remote,GameIOContext.Settings),GameIOContext.Settings)!;
var joined=new Player{chara=reloaded,totalFeat=999,bankMoney=444,hotbars=new(){Slot=1}};
SoloPlayerProfile.RestoreFor(reloaded,joined);
Check(joined.totalFeat==hostTotal&&joined.hotbars.Slot==6&&joined.knownSongs["song"]==12&&joined.wellWished,"host save serialization and rejoin restore client's personal progress");
Check(joined.bankMoney==444&&joined.recipes.craftedRecipes.Contains("axe"),"rejoin restores only personal data, keeping shared finances and recipes");
Check(joined.hotbars.Items.Single() is HotItemAbility{Alias:"pray"},"native polymorphic hotbar type survives validation and rejoin");
var nextSession=new PlayerProfileChannel(reloaded.uid,Guid.NewGuid());
Check(nextSession.Accept(reloaded,second)==null,"reconnect rejects checkpoints from prior save probe");
var legacy=new Chara{uid=777};var legacyPlayer=new Player{chara=legacy,totalFeat=999};
SoloPlayerProfile.RestoreFor(legacy,legacyPlayer);SoloPlayerProfile.Capture(legacy,legacyPlayer);
Check(legacyPlayer.totalFeat==0&&SoloPlayerProfile.HasMissingHistory(legacy),"legacy join never adopts host counters or claims recovered history");
var oldProfile=JObject.Parse(reloaded.GetStr(SoloPlayerProfile.SaveKey)!);oldProfile.Remove("LegacyHistoryMissing");
reloaded.SetStr(SoloPlayerProfile.SaveKey,oldProfile.ToString());reloaded.SetInt(SoloCharacterSelection.OriginalHostKey,1);
Check(SoloPlayerProfile.HasMissingHistory(reloaded),"older selector guest profiles without provenance remain marked incomplete");
var oldHost=new Chara{uid=1};oldHost.SetInt(SoloCharacterSelection.OriginalHostKey,1);oldHost.SetBool("remote_chara",true);oldHost.SetStr(SoloPlayerProfile.SaveKey,oldProfile.ToString());
Check(!SoloPlayerProfile.HasMissingHistory(oldHost),"older original host profile is not mistaken for guest defaults when parked");
var barrier=new PlayerProfileSaveBarrier();
var ask=barrier.Add(10,EClass.pc.uid,session);var askOther=barrier.Add(20,fresh.uid,Guid.NewGuid());
Check(!barrier.Complete&&barrier.Owns(10,EClass.pc.uid)&&!barrier.Owns(20,EClass.pc.uid),"save waits for each registered player, with exact ownership");
var unchanged=sender.Capture(EClass.pc,EClass.player,ask.RequestId)!;
Check(unchanged!=null&&unchanged.RequestId==barrier.Id,"explicit host save gets a reply even when prior data was acknowledged");
PlayerProfileReceipt Receipt(PlayerProfileRequest r,Guid? request=null)=>new(){OwnerUid=r.OwnerUid,Session=r.Session,RequestId=request??r.RequestId,Revision=5};
barrier.Receive(10,Receipt(ask,Guid.NewGuid()));barrier.Receive(10,Receipt(askOther));barrier.Receive(99,Receipt(ask));
Check(!barrier.Complete,"stale request, wrong owner and unregistered peer cannot finish save");
barrier.Receive(10,Receipt(ask));barrier.Receive(10,Receipt(ask));
Check(!barrier.Complete,"duplicate first-player reply cannot substitute for second player");
barrier.Receive(20,Receipt(askOther));Check(barrier.Complete,"all matching fresh replies release save barrier");
var freshBarrier=new PlayerProfileSaveBarrier();freshBarrier.Add(10,ask.OwnerUid,ask.Session);freshBarrier.Receive(10,Receipt(ask));
Check(!freshBarrier.Complete,"previous save receipt cannot complete next save");
var ready=false;var receives=0;
Check(PlayerProfileReplyWait.Run(()=>{receives++;ready=true;},()=>ready,()=>true)&&receives==1,"save wait completes after receiving its reply");
receives=0;Check(PlayerProfileReplyWait.Run(()=>receives++,()=>true,()=>true)&&receives==0,"already complete save never polls");
Check(!PlayerProfileReplyWait.Run(()=>{},()=>false,()=>true,5),"nonresponsive client times out instead of reporting saved");
Check(!PlayerProfileReplyWait.Run(()=>throw new Exception("must not receive"),()=>false,()=>false),"disconnected or changed world aborts save immediately");
ready=false;var alive=true;
Check(!PlayerProfileReplyWait.Run(()=>{ready=true;alive=false;},()=>ready,()=>alive),"disconnect during final reply cannot report save success");
var inbox=new ElinTogether.Net.Steam.SteamNetPacketInbox();var peer=new ElinTogether.Net.Steam.FakeProfilePeer();var seen=new List<string>();
inbox.Add("move-A",peer);inbox.Add(Receipt(ask),peer);inbox.Add("move-B",peer);
inbox.Dispatch((p,_)=>seen.Add(p is PlayerProfileReceipt?"profile":(string)p),p=>p is PlayerProfileReceipt);
Check(seen.SequenceEqual(new[]{"profile"}),"save wait dispatches profile replies only, never gameplay");
inbox.Dispatch((p,_)=>seen.Add((string)p));
Check(seen.SequenceEqual(new[]{"profile","move-A","move-B"}),"deferred gameplay resumes in original order");
seen.Clear();inbox.Add("save-trigger",peer);inbox.Add("move-C",peer);inbox.Add(Receipt(ask),peer);inbox.Add("move-D",peer);
inbox.Dispatch((p,_)=>{seen.Add((string)p);if((string)p=="save-trigger")inbox.Dispatch((_,_)=>seen.Add("nested-profile"),p=>p is PlayerProfileReceipt);});
Check(seen.SequenceEqual(new[]{"save-trigger","nested-profile","move-C","move-D"}),"nested save receive preserves remaining outer batch and gameplay order");
peer.Connected=false;inbox.Add("stale",peer);inbox.Dispatch((_,_)=>throw new Exception("disconnected peer dispatched"));
Check(true,"deferred packets from disconnected peers are dropped");
// Offline companion lifecycle uses the production service, including save/backup.
NetSession.Instance.Connection=null;
EClass.game=new Game();zone=new Zone{uid=7};
original=new Chara{uid=1,homeZone=zone,currentZone=zone};
guest=new Chara{uid=719,homeZone=zone,currentZone=zone};
guest.SetBool("remote_chara",true);
EClass.game.cards.globalCharas[1]=original;EClass.game.cards.globalCharas[719]=guest;
EClass.player.chara=original;EClass.player.uidChara=1;EClass.player.zone=zone;
party=new Party();party.AddMemeber(original);party.SetLeader(original);
tool=new Thing{uid=900,id="axe"};guest.things.Add(tool);guest.equipment=tool;
SoloPlayerProfile.Initialize(guest,legacy:false);
var companionProfile=guest.GetStr(SoloPlayerProfile.SaveKey);
guest.SetInt(PersonalKarma.ValueKey,-9);
PersonalFaith.Save(guest,new PersonalFaith.State{Days=17,PrayerDay=20});
var companionFaith=guest.GetStr(PersonalFaith.SaveKey);
Game.FailSave=true;Reject(()=>SoloCompanions.Recruit(guest),"failed pre-recruit save leaves dormant character untouched");Game.FailSave=false;
Check(guest.party==null&&!SoloCompanions.IsCompanion(guest),"failed recruit never activates companion role");
SoloCompanions.Recruit(guest);
Check(guest.CompanionAI&&guest.party==party&&zone.Active.Contains(guest)&&guest.parent==zone,"same-zone dormant character becomes a real map companion with native AI");
Check(ReferenceEquals(guest.equipment,tool)&&guest.things.Single()==tool&&EClass.game.cards.globalCharas.Count==2,"recruit reuses original character and equipment without clones");
Check(guest.GetStr(SoloPlayerProfile.SaveKey)==companionProfile&&guest.GetStr(PersonalFaith.SaveKey)==companionFaith&&guest.GetInt(PersonalKarma.ValueKey)==-9,"companion recruitment preserves personal profile, karma and faith records");
Check(SoloCompanions.KeepOnOfflineLoad(guest),"offline cleanup keeps opted-in party companion");
Reject(()=>SoloCompanions.Recruit(guest),"repeated recruitment cannot duplicate a party member");
guest.ride=original;
Reject(()=>SoloCompanions.Dismiss(guest),"mounted companion cannot be parked");
Check(SoloCompanions.PrepareHosting()!=null&&guest.CompanionAI,"hosting rejects attached companion before taking away control");guest.ride=null;
tool.Num=5;guest.LV=15;
SoloCompanions.Dismiss(guest);
Check(!guest.CompanionAI&&guest.parent==null&&guest.currentZone==null&&guest.party==null&&!zone.Active.Contains(guest),"dismiss removes AI and map/party membership without destroying the character");
Check(guest.LV==15&&guest.equipment==tool&&tool.Num==5&&guest.GetBool("remote_chara"),"companion progression and item changes survive dismissal as saved human");
SoloCompanions.Recruit(guest);
NetSession.Instance.Connection=new ElinNetHost();
Check(!SoloCompanions.KeepOnOfflineLoad(guest),"companion cleanup exemption never applies in multiplayer");
Reject(()=>SoloCompanions.Recruit(guest),"live multiplayer cannot recruit a human into AI");
Check(SoloCompanions.PrepareHosting()==null&&!SoloCompanions.IsCompanion(guest)&&guest.party==null&&!guest.CompanionAI,"hosting parks solo companion before peers can join");
NetSession.Instance.Connection=null;
SoloCompanions.Recruit(guest);
EClass.game.Save();Game.Load(Game.id,false);
guest=EClass.game.cards.globalCharas.Find(719)!;
Check(SoloCompanions.KeepOnOfflineLoad(guest)&&EClass.pc.party!.uidMembers.Contains(719),"companion opt-in and serialized party survive save/reload");
SoloCharacterSelection.Select(guest);
Check(EClass.pc.uid==719&&!EClass.pc.GetBool(SoloCompanions.Key)&&!EClass.pc.GetBool("remote_chara"),"playing as companion clears AI role while retaining character identity");
original=EClass.game.cards.globalCharas.Find(1)!;
Check(original.party==null&&!SoloCompanions.IsCompanion(original),"switching to companion still parks the former human by default");
SoloCompanions.Recruit(original);
Check(SoloCompanions.IsCompanion(original)&&original.party==EClass.pc.party,"original host can also become companion of selected client");
original.isDead=true;SoloCompanions.Dismiss(original);
Check(original.isDead&&!SoloCompanions.IsCompanion(original),"dead companion can be dismissed without revival or erased death state");
Reject(()=>SoloCompanions.Recruit(original),"dead saved human cannot be revived through recruitment");
Console.WriteLine($"{checks} checks passed; fixture exports: {CorePath.PathBackup}");
