using ElinTogether.Models;
int checks=0;
void Check(bool ok,string label) {if(!ok)throw new Exception(label);checks++;Console.WriteLine("PASS "+label);}
Condition Make(int stat,int kind,int turns=20)=>new(){id=5,_ints=[turns,341,stat,kind,6]};
var host=new Chara(); var client=new Chara();
host.conditions.Add(Make(79,222));
var packet=ConditionSync.Capture(host,5);
ConditionSync.Apply(client,5,packet);
var slow=client.conditions.Single();
Check(slow.refVal==79 && slow.refVal2==222,"slow keeps speed and negative-effect identity");
Check(slow._ints.SequenceEqual([20,341,79,222,6]),"resolved duration power and flags preserved exactly");
Check(slow.owner==client && slow.elements?.Parent==client,"native restore attaches stat effects to owner");
ConditionSync.Apply(client,5,packet);
Check(client.conditions.Count==1 && slow.Effects==1 && slow.Binds==1,"duplicate state does not replay effects or rebind");
host.conditions[0]._ints[0]=45;
var oldContainer=slow.elements;
ConditionSync.Apply(client,5,ConditionSync.Capture(host,5));
Check(ReferenceEquals(slow,client.conditions.Single()) && slow._ints[0]==45,"stack refresh updates existing identity and absolute duration");
Check(oldContainer?.Parent==null && slow.elements?.Parent==client,"old derived stats detached before rebuild");
Check(slow.phase==4 && slow.Effects==1,"phase updates without a repeated start effect");
host.conditions.Add(Make(70,221));
ConditionSync.Apply(client,5,ConditionSync.Capture(host,5));
var strength=client.conditions.Single(c=>c.refVal==70);
Check(client.conditions.Count==2 && strength.refVal2==221,"multiple stat instances coexist");
host.conditions.RemoveAt(0);
ConditionSync.Apply(client,5,ConditionSync.Capture(host,5));
Check(client.conditions.Count==1 && ReferenceEquals(strength,client.conditions[0]) && slow.Removed==1,"removing slow preserves strength buff of same type");
host.conditions[0]=Make(70,222);
ConditionSync.Apply(client,5,ConditionSync.Capture(host,5));
Check(strength.Removed==1 && client.conditions.Single().refVal2==222,"opposite stat effect replaces correct instance");
host.conditions.Clear();ConditionSync.Apply(client,5,ConditionSync.Capture(host,5));
Check(client.conditions.Count==0,"empty resolved family clears expired or nullified status");
var special=new SpecialCondition {id=9,_ints=[12,99,3,4,6]};special.SetExtra(123);host.conditions.Add(special);
ConditionSync.Apply(client,9,ConditionSync.Capture(host,9));
var restored=(SpecialCondition)client.conditions.Single();
Check(restored.Extra==123 && client.ai.Cancels==1 && client.Refreshes==1,"private subclass state restores with native owner hooks");
special.SetExtra(456);ConditionSync.Apply(client,9,ConditionSync.Capture(host,9));
Check(restored.Extra==456 && client.ai.Cancels==1,"subclass refresh updates in place without repeating interruption");
var bad=Make(1,2);bad.id=99;ConditionSync.Apply(client,9,LZ4Bytes.Create(new[]{bad}));
Check(ReferenceEquals(client.conditions.Single(),restored),"mismatched family rejected without mutation");
bad.id=9;bad._ints=[1];ConditionSync.Apply(client,9,LZ4Bytes.Create(new[]{bad}));
Check(ReferenceEquals(client.conditions.Single(),restored),"malformed native state rejected before mutation");
host.conditions.Add(new ConTransmute {id=11,_ints=[20,99,0,0,0]});ConditionSync.Apply(client,11,ConditionSync.Capture(host,11));
Check(client.conditions.OfType<ConTransmute>().Single().Changes==1,"transformation presentation refreshed without OnStart gameplay");
Console.WriteLine($"{checks} checks passed");
